import { CardTheme, CardCategory } from '@/types/cardTheme';

export const CARD_CATEGORIES: CardCategory[] = [
  'Payment',
  'Fluid & Organic',
  'Abstract & Geometric',
  'Business',
  'Neo-Brutalist',
  'Modern',
  'Minimal',
  'Luxury & Gold',
  'Pastel & Soft',
  'Tech & Cyber',
  'Restaurant & Cafe',
  'Event & Pass',
  'Creative & Pop',
  'Dark & Neon',
];

export const CARD_THEMES: CardTheme[] = [
  // =========================================================================
  // 1. PAYMENT & QRIS THEMES (Inspired by official Indonesian & Global Standards)
  // =========================================================================
  {
    id: 'qris-merchant-pro',
    name: 'QRIS Official Merchant Pro',
    category: 'Payment',
    description: 'Format standar QRIS nasional dengan badge merchant, nama toko tebal, dan tombol Scan to Pay.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 4, radius: 28 },
    cardShadow: { color: '#000000', offsetX: 8, offsetY: 8, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 20, padding: 20, size: 420 },
    header: {
      badgeText: 'MERCHANT QR CARD',
      badgeBg: '#FFE600',
      badgeTextColor: '#000000',
      badgeBorderColor: '#000000',
      titleColor: '#000000',
      subtitleColor: '#6B7280',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN TO PAY',
      ctaBg: '#FFE600',
      ctaTextColor: '#000000',
      ctaBorderColor: '#000000',
      ctaRadius: 25,
      hintText: 'Buka kamera smartphone atau aplikasi e-wallet untuk scan',
      hintColor: '#374151',
      subText: 'SUPPORTS ALL MOBILE BANKING & QRIS E-WALLETS',
      subTextColor: '#9CA3AF',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#000000',
    },
  },
  {
    id: 'qris-red-national',
    name: 'QRIS Merah Putih Standard',
    category: 'Payment',
    description: 'Aksen merah putih nasional dengan header patriotik dan kontras tinggi.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#B91C1C', width: 4, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#B91C1C', borderWidth: 3, radius: 18, padding: 20, size: 420 },
    header: {
      badgeText: 'STANDAR PEMBAYARAN NASIONAL',
      badgeBg: '#DC2626',
      badgeTextColor: '#FFFFFF',
      badgeBorderColor: '#B91C1C',
      titleColor: '#1F2937',
      subtitleColor: '#DC2626',
      align: 'center',
    },
    footer: {
      ctaText: 'BAYAR DENGAN QRIS',
      ctaBg: '#DC2626',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#991B1B',
      ctaRadius: 14,
      hintText: 'Scan menggunakan BCA, Mandiri, BRI, GoPay, OVO, Dana',
      hintColor: '#4B5563',
      subText: 'TERDAFTAR & DIAWASI BANK INDONESIA',
      subTextColor: '#9CA3AF',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#DC2626',
    },
  },
  {
    id: 'payment-bca-royal',
    name: 'Royal Blue E-Banking',
    category: 'Payment',
    description: 'Sentuhan biru bank profesional dengan frame bersih dan kejelasan ultra-tinggi.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#F8FAFC',
    cardBorder: { color: '#0284C7', width: 3.5, radius: 24 },
    cardShadow: { color: '#0369A1', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#0284C7', borderWidth: 2.5, radius: 18, padding: 18, size: 420 },
    header: {
      badgeText: 'VERIFIED MERCHANT',
      badgeBg: '#0284C7',
      badgeTextColor: '#FFFFFF',
      titleColor: '#0F172A',
      subtitleColor: '#0369A1',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN DISINI UNTUK BAYAR',
      ctaBg: '#0284C7',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#0369A1',
      ctaRadius: 14,
      hintText: 'Mendukung semua aplikasi perbankan digital & QRIS',
      hintColor: '#334155',
      subText: 'INSTANT CONFIRMATION & SECURE TRANSACTION',
      subTextColor: '#94A3B8',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#0284C7',
    },
  },
  {
    id: 'payment-emerald-trust',
    name: 'Fintech Emerald Trust',
    category: 'Payment',
    description: 'Nuansa hijau emerald fintech modern yang memberi rasa aman dan terpercaya.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#F0FDF4',
    cardBorder: { color: '#15803D', width: 3.5, radius: 26 },
    cardShadow: { color: '#166534', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#16A34A', borderWidth: 3, radius: 20, padding: 18, size: 420 },
    header: {
      badgeText: 'SECURE CASHLESS PAYMENT',
      badgeBg: '#16A34A',
      badgeTextColor: '#FFFFFF',
      titleColor: '#14532D',
      subtitleColor: '#15803D',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN & BAYAR SEKARANG',
      ctaBg: '#16A34A',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#14532D',
      ctaRadius: 24,
      hintText: 'Arahkan kamera smartphone ke kode QR di atas',
      hintColor: '#166534',
      subText: 'ZERO TRANSACTION FEE • 100% ENCRYPTED',
      subTextColor: '#86EFAC',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#22C55E',
      secondaryColor: '#BBF7D0',
    },
  },
  {
    id: 'payment-purple-pay',
    name: 'Digital Purple Wallet',
    category: 'Payment',
    description: 'Gaya e-wallet ungu elektrik dengan badge premium dan rounded pill.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FAF5FF',
    cardBorder: { color: '#7E22CE', width: 3.5, radius: 28 },
    cardShadow: { color: '#581C87', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#9333EA', borderWidth: 3, radius: 22, padding: 18, size: 420 },
    header: {
      badgeText: 'DIGITAL WALLET QR',
      badgeBg: '#9333EA',
      badgeTextColor: '#FFFFFF',
      titleColor: '#3B0764',
      subtitleColor: '#7E22CE',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN TO PAY CASHLESS',
      ctaBg: '#9333EA',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#581C87',
      ctaRadius: 25,
      hintText: 'Buka OVO, GoPay, Dana, ShopeePay atau Mobile Banking',
      hintColor: '#6B21A8',
      subText: 'OFFICIAL CASHLESS PAYMENT POINT',
      subTextColor: '#C084FC',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#A855F7',
      secondaryColor: '#E9D5FF',
    },
  },
  {
    id: 'payment-orange-shopee',
    name: 'Sunset Orange Merchant',
    category: 'Payment',
    description: 'Warna oranye cerah energetik cocok untuk restoran, cafe, dan gerai retail.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFF7ED',
    cardBorder: { color: '#EA580C', width: 4, radius: 26 },
    cardShadow: { color: '#9A3412', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#EA580C', borderWidth: 3, radius: 20, padding: 18, size: 420 },
    header: {
      badgeText: 'KASIR & CHECKOUT CEPAT',
      badgeBg: '#F97316',
      badgeTextColor: '#FFFFFF',
      titleColor: '#7C2D12',
      subtitleColor: '#C2410C',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN UNTUK MENYELESAIKAN ORDER',
      ctaBg: '#EA580C',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#7C2D12',
      ctaRadius: 18,
      hintText: 'Pastikan nama penerima dan nominal sudah sesuai di layar',
      hintColor: '#9A3412',
      subText: 'INSTANT DIGITAL RECEIPT SENT TO APP',
      subTextColor: '#FDBA74',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#F97316',
    },
  },
  {
    id: 'payment-dark-vault',
    name: 'Midnight Black Vault Pay',
    category: 'Payment',
    description: 'Kartu bayar hitam pekat eksklusif dengan aksen kuning neon neo-brutalist.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#121212',
    cardBorder: { color: '#FFE600', width: 4, radius: 24 },
    cardShadow: { color: '#FFE600', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#FFE600', borderWidth: 3, radius: 18, padding: 18, size: 420 },
    header: {
      badgeText: 'EXCLUSIVE SECURE PAY',
      badgeBg: '#FFE600',
      badgeTextColor: '#000000',
      titleColor: '#FFFFFF',
      subtitleColor: '#FFE600',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN HERE • INSTANT PAY',
      ctaBg: '#FFE600',
      ctaTextColor: '#000000',
      ctaBorderColor: '#FFFFFF',
      ctaRadius: 25,
      hintText: 'Point any camera or QR scanner at the matrix',
      hintColor: '#D1D5DB',
      subText: 'ENCRYPTED • END-TO-END VERIFIED',
      subTextColor: '#9CA3AF',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#FFE600',
    },
  },

  // =========================================================================
  // 2. FLUID & ORGANIC WAVES (Directly based on User Uploaded Images 1, 2, 3)
  // =========================================================================
  {
    id: 'fluid-coral-sun',
    name: 'Coral & Sun Fluid Waves',
    category: 'Fluid & Organic',
    description: 'Lekukan gelombang cerah kuning & coral pink dengan ornamen gelembung dan kutipan (seperti Gambar 1).',
    layout: 'fluid-wave-bottom',
    dimensions: { width: 640, height: 640 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 3, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 16, size: 280, yOffset: 250 },
    header: {
      badgeText: 'SCAN ME',
      titleColor: '#1F2937',
      subtitleColor: '#6B7280',
      align: 'left',
    },
    footer: {
      ctaText: 'CR CODE',
      ctaBg: '#FFE600',
      ctaTextColor: '#000000',
    },
    decoration: {
      type: 'waves-dual',
      primaryColor: '#FFE600',
      secondaryColor: '#FF5E5B',
      accentColor: '#FFFFFF',
      detailColor: '#000000',
    },
  },
  {
    id: 'fluid-coral-top-wave',
    name: 'Sunset Coral Top Swirl',
    category: 'Fluid & Organic',
    description: 'Gelombang melengkung tebal di atas dengan lingkaran floating dan QR di tengah bawah (Gambar 1 b).',
    layout: 'fluid-wave-bottom',
    dimensions: { width: 640, height: 640 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 3, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 18, padding: 16, size: 280, yOffset: 240 },
    header: {
      titleColor: '#000000',
      subtitleColor: '#4B5563',
      align: 'left',
    },
    footer: {
      ctaText: 'SCAN CODE',
      ctaBg: '#FF5E5B',
      ctaTextColor: '#FFFFFF',
    },
    decoration: {
      type: 'waves-corner',
      primaryColor: '#FF5E5B',
      secondaryColor: '#FFE600',
      accentColor: '#FFFFFF',
      detailColor: '#FF5E5B',
    },
  },
  {
    id: 'fluid-pastel-play',
    name: 'Pastel Sorbet Fluid Card',
    category: 'Fluid & Organic',
    description: 'Warna pastel ungu lilac, kuning lembut, dan hijau mint dengan ornamen kurva cair (Gambar 2).',
    layout: 'organic-blob',
    dimensions: { width: 640, height: 640 },
    cardBg: '#FEF9C3',
    cardBorder: { color: '#000000', width: 3, radius: 40 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 24, padding: 18, size: 290 },
    header: {
      titleColor: '#000000',
      subtitleColor: '#6B7280',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN ME',
      ctaBg: '#C084FC',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 18,
    },
    decoration: {
      type: 'organic-blobs',
      primaryColor: '#C084FC',
      secondaryColor: '#86EFAC',
      accentColor: '#FEF08A',
      detailColor: '#000000',
    },
  },
  {
    id: 'fluid-teal-orange-blob',
    name: 'Teal & Sunset Organic Blob',
    category: 'Fluid & Organic',
    description: 'Kombinasi warna teal toska, oranye tangerine, dan krem dengan frame blob melingkari QR (Gambar 2 c).',
    layout: 'organic-blob',
    dimensions: { width: 640, height: 640 },
    cardBg: '#FFFBEB',
    cardBorder: { color: '#000000', width: 3, radius: 40 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 26, padding: 18, size: 290 },
    header: {
      titleColor: '#1E293B',
      subtitleColor: '#64748B',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN ME',
      ctaBg: '#0EA5E9',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 18,
    },
    decoration: {
      type: 'organic-blobs',
      primaryColor: '#0284C7',
      secondaryColor: '#F97316',
      accentColor: '#FDE047',
      detailColor: '#0284C7',
    },
  },
  {
    id: 'badge-warm-mustard',
    name: 'Warm Mustard Table Standee',
    category: 'Fluid & Organic',
    description: 'Kartu vertikal standee meja dengan gelombang mustard, oranye hangat, dan lingkaran retro (Gambar 3 a).',
    layout: 'badge-vertical',
    dimensions: { width: 600, height: 860 },
    cardBg: '#F59E0B',
    cardBorder: { color: '#000000', width: 3.5, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 240 },
    header: {
      badgeText: 'CHECK IN',
      titleColor: '#000000',
      subtitleColor: '#1F2937',
      align: 'left',
    },
    footer: {
      ctaText: 'QR CODE',
      ctaBg: '#EA580C',
      ctaTextColor: '#FFFFFF',
      ctaBorderColor: '#000000',
      ctaRadius: 16,
    },
    decoration: {
      type: 'checkin-badge',
      primaryColor: '#D97706',
      secondaryColor: '#0284C7',
      accentColor: '#FDE68A',
      detailColor: '#000000',
    },
  },
  {
    id: 'badge-sage-wave',
    name: 'Sage Green Organic Standee',
    category: 'Fluid & Organic',
    description: 'Kartu standee nuansa hijau sage pastel dan teal laut yang menyegarkan dan santai (Gambar 3 b).',
    layout: 'badge-vertical',
    dimensions: { width: 600, height: 860 },
    cardBg: '#A7F3D0',
    cardBorder: { color: '#000000', width: 3.5, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 240 },
    header: {
      badgeText: 'WELCOME',
      titleColor: '#064E3B',
      subtitleColor: '#065F46',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN ME',
      ctaBg: '#059669',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 18,
    },
    decoration: {
      type: 'waves-dual',
      primaryColor: '#6EE7B7',
      secondaryColor: '#0D9488',
      accentColor: '#FFFFFF',
      detailColor: '#064E3B',
    },
  },
  {
    id: 'badge-sky-cloud',
    name: 'Sky Blue Cloud Wave',
    category: 'Fluid & Organic',
    description: 'Gelombang biru langit, kuning terang, dan merah terakota bergaya modern art poster (Gambar 3 c).',
    layout: 'badge-vertical',
    dimensions: { width: 600, height: 860 },
    cardBg: '#BAE6FD',
    cardBorder: { color: '#000000', width: 3.5, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 240 },
    header: {
      badgeText: 'QR CODE',
      titleColor: '#0C4A6E',
      subtitleColor: '#0369A1',
      align: 'right',
    },
    footer: {
      ctaText: 'SCAN TO CONNECT',
      ctaBg: '#0284C7',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 18,
    },
    decoration: {
      type: 'waves-corner',
      primaryColor: '#FDE047',
      secondaryColor: '#EF4444',
      accentColor: '#38BDF8',
      detailColor: '#0C4A6E',
    },
  },
  {
    id: 'badge-charcoal-mustard',
    name: 'Charcoal & Ochre Standee',
    category: 'Fluid & Organic',
    description: 'Kontras dramatis arang abu gelap dengan kurva kuning ochre dan biru kobalt (Gambar 3 d).',
    layout: 'badge-vertical',
    dimensions: { width: 600, height: 860 },
    cardBg: '#18181B',
    cardBorder: { color: '#000000', width: 3.5, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 240 },
    header: {
      titleColor: '#FFFFFF',
      subtitleColor: '#E4E4E7',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN ME',
      ctaBg: '#FACC15',
      ctaTextColor: '#000000',
      ctaRadius: 18,
    },
    decoration: {
      type: 'waves-dual',
      primaryColor: '#EAB308',
      secondaryColor: '#2563EB',
      accentColor: '#FFFFFF',
      detailColor: '#FACC15',
    },
  },
  {
    id: 'badge-terracotta-crimson',
    name: 'Terracotta & Crimson Rhythm',
    category: 'Fluid & Organic',
    description: 'Warna hangat marun, terakota, dan oranye dengan ornamen bintang diamond ritmik (Gambar 3 f).',
    layout: 'badge-vertical',
    dimensions: { width: 600, height: 860 },
    cardBg: '#EA580C',
    cardBorder: { color: '#000000', width: 3.5, radius: 36 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 240 },
    header: {
      badgeText: 'QR CODE',
      titleColor: '#FFFFFF',
      subtitleColor: '#FED7AA',
      align: 'center',
    },
    footer: {
      ctaText: 'TAP OR SCAN',
      ctaBg: '#7C2D12',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 16,
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#7C2D12',
      secondaryColor: '#FACC15',
      accentColor: '#FFFFFF',
      detailColor: '#000000',
    },
  },

  // =========================================================================
  // 3. ABSTRACT & GEOMETRIC CUTS (Based on User Uploaded Image 4)
  // =========================================================================
  {
    id: 'geo-tech-yellow-purple',
    name: 'Tech Angle Yellow & Slate',
    category: 'Abstract & Geometric',
    description: 'Potongan diagonal modern arang hitam, kuning tajam, dan aksen ungu (seperti Gambar 4 a).',
    layout: 'diagonal-split',
    dimensions: { width: 640, height: 640 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 3, radius: 28 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#7C3AED', borderWidth: 3.5, radius: 14, padding: 14, size: 280, yOffset: 120 },
    header: {
      badgeText: 'CHECK IN',
      badgeBg: '#F59E0B',
      badgeTextColor: '#FFFFFF',
      titleColor: '#000000',
      subtitleColor: '#6B7280',
      align: 'left',
    },
    footer: {
      ctaText: 'QRCODE',
      ctaBg: '#F59E0B',
      ctaTextColor: '#000000',
    },
    decoration: {
      type: 'diagonal-stripes',
      primaryColor: '#FBBF24',
      secondaryColor: '#1E293B',
      accentColor: '#8B5CF6',
      detailColor: '#FFFFFF',
    },
  },
  {
    id: 'geo-chevron-purple-banner',
    name: 'Chevron Slate & Violet Pass',
    category: 'Abstract & Geometric',
    description: 'Garis sudut tegas chevron dengan banner ungu tebal dan label ATTENTION PLEASE (Gambar 4 b).',
    layout: 'diagonal-split',
    dimensions: { width: 600, height: 860 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 3.5, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 16, padding: 18, size: 360, yOffset: 160 },
    header: {
      badgeText: 'CHECK IN',
      titleColor: '#FFFFFF',
      subtitleColor: '#CBD5E1',
      align: 'left',
    },
    footer: {
      ctaText: 'QRCODE',
      ctaBg: '#7C3AED',
      ctaTextColor: '#FFFFFF',
      hintText: 'ATTENTION PLEASE • SCAN BEFORE ENTERING',
      hintColor: '#E2E8F0',
    },
    decoration: {
      type: 'diagonal-stripes',
      primaryColor: '#1E293B',
      secondaryColor: '#F59E0B',
      accentColor: '#7C3AED',
      detailColor: '#FFFFFF',
    },
  },
  {
    id: 'geo-card-gold-frame',
    name: 'Slate Angle Golden Stage',
    category: 'Abstract & Geometric',
    description: 'Frame kotak emas menonjol dengan latar belakang diagonal hitam dan ornamen 3 titik (Gambar 4 c).',
    layout: 'diagonal-split',
    dimensions: { width: 600, height: 860 },
    cardBg: '#1E293B',
    cardBorder: { color: '#000000', width: 3.5, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#F59E0B', borderWidth: 8, radius: 16, padding: 16, size: 360, yOffset: 230 },
    header: {
      badgeText: 'CHECK IN',
      titleColor: '#FFFFFF',
      subtitleColor: '#FCD34D',
      align: 'left',
    },
    footer: {
      ctaText: 'SCAN ME',
      ctaBg: '#F59E0B',
      ctaTextColor: '#000000',
    },
    decoration: {
      type: 'diagonal-stripes',
      primaryColor: '#0F172A',
      secondaryColor: '#FFFFFF',
      accentColor: '#F59E0B',
      detailColor: '#FFFFFF',
    },
  },
  {
    id: 'geo-split-tri-color',
    name: 'Tri-Tone Prism Stand',
    category: 'Abstract & Geometric',
    description: 'Komposisi geometris segitiga prisma ungu, kuning, dan biru gelap (Gambar 4 d).',
    layout: 'diagonal-split',
    dimensions: { width: 600, height: 640 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 3, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 3, radius: 14, padding: 14, size: 290, yOffset: 190 },
    header: {
      badgeText: 'SCAN ME',
      badgeBg: '#F59E0B',
      badgeTextColor: '#000000',
      titleColor: '#FFFFFF',
      subtitleColor: '#E2E8F0',
      align: 'center',
    },
    footer: {
      ctaText: 'DIRECT SCAN',
      ctaBg: '#7C3AED',
      ctaTextColor: '#FFFFFF',
    },
    decoration: {
      type: 'diagonal-stripes',
      primaryColor: '#7C3AED',
      secondaryColor: '#F59E0B',
      accentColor: '#1E293B',
      detailColor: '#FFFFFF',
    },
  },

  // =========================================================================
  // 4. NEO-BRUTALIST THEMES (High Contrast, Bold Borders, Stark Energy)
  // =========================================================================
  {
    id: 'brutal-high-voltage',
    name: 'Brutalist High Voltage',
    category: 'Neo-Brutalist',
    description: 'Kuning neon mentah dengan border hitam 5px, stiker miring, dan bayangan offset tajam.',
    layout: 'brutalist-block',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFE600',
    cardBorder: { color: '#000000', width: 5, radius: 0 },
    cardShadow: { color: '#000000', offsetX: 10, offsetY: 10, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 4, radius: 0, padding: 20, size: 420 },
    header: {
      badgeText: '// RAW POWER QR',
      badgeBg: '#000000',
      badgeTextColor: '#FFE600',
      badgeBorderColor: '#000000',
      titleColor: '#000000',
      subtitleColor: '#1F2937',
      align: 'center',
    },
    footer: {
      ctaText: '[ POINT YOUR LENS HERE ]',
      ctaBg: '#000000',
      ctaTextColor: '#FFE600',
      ctaBorderColor: '#000000',
      ctaRadius: 0,
      hintText: 'HARDWARE ACCELERATED OPTICAL DATA MATRIX',
      hintColor: '#000000',
      subText: 'SYSTEM STATUS: ONLINE // ZERO LATENCY',
      subTextColor: '#374151',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#000000',
    },
  },
  {
    id: 'brutal-bubblegum-pink',
    name: 'Brutal Bubblegum Shock',
    category: 'Neo-Brutalist',
    description: 'Merah muda bubblegum intens dengan teks tebal dan kontras hitam pekat.',
    layout: 'brutalist-block',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FF69B4',
    cardBorder: { color: '#000000', width: 5, radius: 12 },
    cardShadow: { color: '#000000', offsetX: 9, offsetY: 9, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 4, radius: 8, padding: 20, size: 420 },
    header: {
      badgeText: '★ SCAN THE DROP ★',
      badgeBg: '#FFE600',
      badgeTextColor: '#000000',
      titleColor: '#000000',
      subtitleColor: '#000000',
      align: 'center',
    },
    footer: {
      ctaText: 'TAP / SCAN TO ENTER',
      ctaBg: '#000000',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 6,
      hintText: 'Exclusive drop • Limited edition merchandise',
      hintColor: '#000000',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#000000',
      secondaryColor: '#FFE600',
    },
  },
  {
    id: 'brutal-toxic-lime',
    name: 'Toxic Cyber Lime',
    category: 'Neo-Brutalist',
    description: 'Hijau lime radioaktif dengan tipografi industrial dan gridline kasar.',
    layout: 'brutalist-block',
    dimensions: { width: 640, height: 880 },
    cardBg: '#70EE9C',
    cardBorder: { color: '#000000', width: 4.5, radius: 0 },
    cardShadow: { color: '#000000', offsetX: 8, offsetY: 8, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 4, radius: 0, padding: 20, size: 420 },
    header: {
      badgeText: 'SECURE_ACCESS_NODE',
      badgeBg: '#000000',
      badgeTextColor: '#70EE9C',
      titleColor: '#000000',
      subtitleColor: '#064E3B',
      align: 'center',
    },
    footer: {
      ctaText: 'EXECUTE OPTICAL SCAN',
      ctaBg: '#000000',
      ctaTextColor: '#70EE9C',
      ctaRadius: 0,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#000000',
    },
  },
  {
    id: 'brutal-monochrome-raw',
    name: 'Stark Monochrome Raw',
    category: 'Neo-Brutalist',
    description: 'Hitam putih murni dengan ketebalan garis maksimal dan tanpa distraksi warna.',
    layout: 'brutalist-block',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#000000', width: 6, radius: 0 },
    cardShadow: { color: '#000000', offsetX: 10, offsetY: 10, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#000000', borderWidth: 4, radius: 0, padding: 20, size: 420 },
    header: {
      badgeText: 'OFFICIAL RECORD',
      badgeBg: '#000000',
      badgeTextColor: '#FFFFFF',
      titleColor: '#000000',
      subtitleColor: '#4B5563',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN TO ACCESS FILE',
      ctaBg: '#000000',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 0,
    },
    decoration: {
      type: 'dots-matrix',
      primaryColor: '#000000',
    },
  },

  // =========================================================================
  // 5. LUXURY & GOLD THEMES (Ultra-Premium, Gold Foil, Fine Serif)
  // =========================================================================
  {
    id: 'luxury-black-gold',
    name: '24K Velvet Gold Luxury',
    category: 'Luxury & Gold',
    description: 'Latar hitam beludru dengan aksen emas murni 24 karat dan bingkai ganda elegan.',
    layout: 'gold-luxury',
    dimensions: { width: 640, height: 880 },
    cardBg: '#0B0B0C',
    cardBorder: { color: '#D4AF37', width: 3, radius: 20 },
    cardShadow: { color: '#000000', offsetX: 8, offsetY: 8, blur: 12 },
    qrContainer: { bg: '#FFFFFF', border: '#D4AF37', borderWidth: 2.5, radius: 12, padding: 18, size: 410 },
    header: {
      badgeText: 'EXECUTIVE PRIVILEGE',
      badgeBg: '#D4AF37',
      badgeTextColor: '#0B0B0C',
      titleColor: '#F5E6BE',
      subtitleColor: '#D4AF37',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN FOR EXCLUSIVE ACCESS',
      ctaBg: '#D4AF37',
      ctaTextColor: '#0B0B0C',
      ctaRadius: 10,
      hintText: 'By invitation only • Concierge VIP service',
      hintColor: '#A39268',
      subText: 'PRIVATE & CONFIDENTIAL MEMBER ACCESS',
      subTextColor: '#736440',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#D4AF37',
      secondaryColor: '#8C7326',
    },
  },
  {
    id: 'luxury-emerald-brass',
    name: 'Imperial Emerald & Brass',
    category: 'Luxury & Gold',
    description: 'Warna hijau zamrud kerajaan dengan detail logam kuningan berkilau.',
    layout: 'gold-luxury',
    dimensions: { width: 640, height: 880 },
    cardBg: '#06281E',
    cardBorder: { color: '#C5A059', width: 3, radius: 22 },
    cardShadow: { color: '#031711', offsetX: 8, offsetY: 8, blur: 10 },
    qrContainer: { bg: '#FFFFFF', border: '#C5A059', borderWidth: 2.5, radius: 14, padding: 18, size: 410 },
    header: {
      badgeText: 'ROYAL HERITAGE',
      badgeBg: '#C5A059',
      badgeTextColor: '#06281E',
      titleColor: '#E6D7B8',
      subtitleColor: '#C5A059',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN TO EXPLORE COLLECTION',
      ctaBg: '#C5A059',
      ctaTextColor: '#06281E',
      ctaRadius: 10,
      hintText: 'Artisanal craftsmanship since 1924',
      hintColor: '#8FA69B',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#C5A059',
    },
  },
  {
    id: 'luxury-rose-champagne',
    name: 'Rose Gold & Champagne',
    category: 'Luxury & Gold',
    description: 'Sentuhan anggun rose gold dan nuansa champagne untuk parfum, butik, dan perhiasan.',
    layout: 'gold-luxury',
    dimensions: { width: 640, height: 880 },
    cardBg: '#1A1418',
    cardBorder: { color: '#E8A598', width: 3, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 8, offsetY: 8, blur: 12 },
    qrContainer: { bg: '#FFFFFF', border: '#E8A598', borderWidth: 2.5, radius: 16, padding: 18, size: 410 },
    header: {
      badgeText: 'HAUTE COUTURE',
      badgeBg: '#E8A598',
      badgeTextColor: '#1A1418',
      titleColor: '#FDECE9',
      subtitleColor: '#E8A598',
      align: 'center',
    },
    footer: {
      ctaText: 'DISCOVER PRIVATE ATELIER',
      ctaBg: '#E8A598',
      ctaTextColor: '#1A1418',
      ctaRadius: 20,
      hintText: 'Bespoke tailoring & fine fragrance catalog',
      hintColor: '#A89299',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#E8A598',
    },
  },
  {
    id: 'luxury-marble-platinum',
    name: 'Carrara Marble & Platinum',
    category: 'Luxury & Gold',
    description: 'Marmer putih Carrara minimalis dengan garis platinum dingin dan bersih.',
    layout: 'gold-luxury',
    dimensions: { width: 640, height: 880 },
    cardBg: '#F8FAFC',
    cardBorder: { color: '#64748B', width: 2.5, radius: 18 },
    cardShadow: { color: '#94A3B8', offsetX: 6, offsetY: 6, blur: 8 },
    qrContainer: { bg: '#FFFFFF', border: '#475569', borderWidth: 2, radius: 12, padding: 18, size: 410 },
    header: {
      badgeText: 'ARCHITECTURAL RESIDENCES',
      badgeBg: '#334155',
      badgeTextColor: '#FFFFFF',
      titleColor: '#0F172A',
      subtitleColor: '#475569',
      align: 'center',
    },
    footer: {
      ctaText: 'VIEW PROPERTY PORTFOLIO',
      ctaBg: '#334155',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 8,
      hintText: 'Private viewing scheduled by appointment',
      hintColor: '#64748B',
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#475569',
    },
  },

  // =========================================================================
  // 6. BUSINESS & CORPORATE THEMES
  // =========================================================================
  {
    id: 'biz-corporate-trust',
    name: 'Global Enterprise Trust',
    category: 'Business',
    description: 'Tata letak korporat formal dengan kode identitas dokumen dan header resmi.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#1E3A8A', width: 3.5, radius: 16 },
    cardShadow: { color: '#0F172A', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#1E3A8A', borderWidth: 2.5, radius: 12, padding: 18, size: 420 },
    header: {
      badgeText: 'CORPORATE VERIFIED ID',
      badgeBg: '#1E3A8A',
      badgeTextColor: '#FFFFFF',
      titleColor: '#1E293B',
      subtitleColor: '#3B82F6',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN FOR COMPANY PROFILE',
      ctaBg: '#1E3A8A',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 10,
      hintText: 'Annual reports, compliance & investor relations',
      hintColor: '#64748B',
      subText: 'ISO 27001 VERIFIED DATA GATEWAY',
      subTextColor: '#94A3B8',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#1E3A8A',
    },
  },
  {
    id: 'biz-modern-consulting',
    name: 'Executive Advisory Slate',
    category: 'Business',
    description: 'Warna abu-abu arang modern dengan aksen cyan untuk konsultan dan firma hukum.',
    layout: 'center-standard',
    dimensions: { width: 640, height: 880 },
    cardBg: '#F1F5F9',
    cardBorder: { color: '#0F172A', width: 3, radius: 16 },
    cardShadow: { color: '#0F172A', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#0F172A', borderWidth: 2.5, radius: 12, padding: 18, size: 420 },
    header: {
      badgeText: 'STRATEGY & ADVISORY',
      badgeBg: '#0F172A',
      badgeTextColor: '#38BDF8',
      titleColor: '#0F172A',
      subtitleColor: '#0284C7',
      align: 'center',
    },
    footer: {
      ctaText: 'SCHEDULE CONSULTATION',
      ctaBg: '#0F172A',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 8,
      hintText: 'Connect directly with senior partner',
      hintColor: '#475569',
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#0284C7',
    },
  },

  // =========================================================================
  // 7. TECH, CYBER & NEON THEMES
  // =========================================================================
  {
    id: 'cyber-neon-matrix',
    name: 'Cyberpunk Neon HUD',
    category: 'Tech & Cyber',
    description: 'Tema masa depan dengan garis pemindaian cyan, grid HUD, dan aksen terminal gelap.',
    layout: 'cyber-grid',
    dimensions: { width: 640, height: 880 },
    cardBg: '#030712',
    cardBorder: { color: '#00F0FF', width: 3, radius: 16 },
    cardShadow: { color: '#00F0FF', offsetX: 6, offsetY: 6, blur: 12 },
    qrContainer: { bg: '#000000', border: '#00F0FF', borderWidth: 3, radius: 8, padding: 18, size: 420 },
    header: {
      badgeText: 'SYSTEM.NODE://INITIALIZE',
      badgeBg: '#00F0FF',
      badgeTextColor: '#030712',
      titleColor: '#00F0FF',
      subtitleColor: '#38BDF8',
      align: 'center',
    },
    footer: {
      ctaText: 'INITIATE OPTICAL HANDSHAKE',
      ctaBg: '#00F0FF',
      ctaTextColor: '#030712',
      ctaRadius: 4,
      hintText: 'QUANTUM ENCRYPTED PROTOCOL 2.0',
      hintColor: '#0284C7',
      subText: 'NODE STATUS: ACTIVE // FREQ 5.8GHZ',
      subTextColor: '#0369A1',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#00F0FF',
    },
  },
  {
    id: 'cyber-synthwave-magenta',
    name: 'Synthwave Neon 1984',
    category: 'Tech & Cyber',
    description: 'Magenta neon berkilau dan garis senja retro synthwave 80-an.',
    layout: 'cyber-grid',
    dimensions: { width: 640, height: 880 },
    cardBg: '#12072B',
    cardBorder: { color: '#F43F5E', width: 3.5, radius: 18 },
    cardShadow: { color: '#E11D48', offsetX: 6, offsetY: 6, blur: 14 },
    qrContainer: { bg: '#FFFFFF', border: '#F43F5E', borderWidth: 3, radius: 12, padding: 18, size: 420 },
    header: {
      badgeText: 'RETRO FUTURE WAVE',
      badgeBg: '#F43F5E',
      badgeTextColor: '#FFFFFF',
      titleColor: '#FDA4AF',
      subtitleColor: '#F43F5E',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN FOR RETRO SOUNDTRACK',
      ctaBg: '#F43F5E',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 12,
      hintText: 'High fidelity audio stream & visualizer',
      hintColor: '#C084FC',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#F43F5E',
      secondaryColor: '#A855F7',
    },
  },

  // =========================================================================
  // 8. RESTAURANT, CAFE & GASTRONOMY
  // =========================================================================
  {
    id: 'cafe-artisan-roastery',
    name: 'Artisan Coffee Roastery',
    category: 'Restaurant & Cafe',
    description: 'Warna espresso gelap, krem berbusa, dan aksen kayu hangat untuk meja cafe.',
    layout: 'cafe-retro',
    dimensions: { width: 600, height: 860 },
    cardBg: '#271B14',
    cardBorder: { color: '#D97706', width: 3.5, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#D97706', borderWidth: 3, radius: 16, padding: 18, size: 380, yOffset: 230 },
    header: {
      badgeText: 'DIGITAL MENU & ORDER',
      badgeBg: '#D97706',
      badgeTextColor: '#FFFFFF',
      titleColor: '#FEF3C7',
      subtitleColor: '#FCD34D',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN UNTUK LIHAT BUKU MENU',
      ctaBg: '#D97706',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 20,
      hintText: 'Pesan langsung dari meja & bayar tanpa antre',
      hintColor: '#FDE68A',
      subText: 'FREE HIGH SPEED WIFI AVAILABLE',
      subTextColor: '#B45309',
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#D97706',
    },
  },
  {
    id: 'cafe-bistro-chalkboard',
    name: 'Bistro Blackboard & Kraft',
    category: 'Restaurant & Cafe',
    description: 'Kombinasi papan kapur hitam dan kertas kraft cokelat bergaya gastropub.',
    layout: 'cafe-retro',
    dimensions: { width: 600, height: 860 },
    cardBg: '#1C1917',
    cardBorder: { color: '#E7E5E4', width: 3, radius: 20 },
    cardShadow: { color: '#0C0A09', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#A8A29E', borderWidth: 3, radius: 14, padding: 18, size: 380, yOffset: 230 },
    header: {
      badgeText: 'TABLE STAND ORDER',
      badgeBg: '#E7E5E4',
      badgeTextColor: '#1C1917',
      titleColor: '#FAFAF9',
      subtitleColor: '#A8A29E',
      align: 'center',
    },
    footer: {
      ctaText: 'VIEW TODAY\'S SPECIALS',
      ctaBg: '#E7E5E4',
      ctaTextColor: '#1C1917',
      ctaRadius: 10,
      hintText: 'Chef signature dishes & craft cocktails',
      hintColor: '#A8A29E',
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#E7E5E4',
    },
  },
  {
    id: 'resto-matcha-japanese',
    name: 'Kyoto Matcha Minimalist',
    category: 'Restaurant & Cafe',
    description: 'Hijau daun teh matcha dengan kertas washi krem zen dan keseimbangan rapi.',
    layout: 'cafe-retro',
    dimensions: { width: 600, height: 860 },
    cardBg: '#F5F5DC',
    cardBorder: { color: '#3F6212', width: 3, radius: 24 },
    cardShadow: { color: '#1A2E05', offsetX: 6, offsetY: 6, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#3F6212', borderWidth: 2.5, radius: 16, padding: 18, size: 380, yOffset: 230 },
    header: {
      badgeText: 'JAPANESE DINING EXPERIENCE',
      badgeBg: '#3F6212',
      badgeTextColor: '#FFFFFF',
      titleColor: '#1A2E05',
      subtitleColor: '#4D7C0F',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN FOR OMAKASE MENU',
      ctaBg: '#3F6212',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 16,
      hintText: 'Fresh seasonal ingredients imported daily',
      hintColor: '#65A30D',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#3F6212',
    },
  },

  // =========================================================================
  // 9. EVENT, TICKET & PASS THEMES
  // =========================================================================
  {
    id: 'pass-vip-backstage',
    name: 'VIP Backstage Access Pass',
    category: 'Event & Pass',
    description: 'Format ID card lanyard vertikal dengan notch tali, nomor barcode, dan stempel ALL ACCESS.',
    layout: 'ticket-pass',
    dimensions: { width: 600, height: 900 },
    cardBg: '#09090B',
    cardBorder: { color: '#EAB308', width: 3.5, radius: 24 },
    cardShadow: { color: '#000000', offsetX: 8, offsetY: 8, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#EAB308', borderWidth: 3, radius: 14, padding: 18, size: 380, yOffset: 260 },
    header: {
      badgeText: '★ VIP ALL ACCESS PASS ★',
      badgeBg: '#EAB308',
      badgeTextColor: '#000000',
      titleColor: '#FFFFFF',
      subtitleColor: '#FACC15',
      align: 'center',
    },
    footer: {
      ctaText: 'SCAN AT SECURITY GATE',
      ctaBg: '#EAB308',
      ctaTextColor: '#000000',
      ctaRadius: 10,
      hintText: 'Must be worn visibly at all times in venue',
      hintColor: '#A1A1AA',
      subText: 'NON-TRANSFERABLE • RFID COMPATIBLE',
      subTextColor: '#71717A',
      showSecurityBadge: true,
    },
    decoration: {
      type: 'corner-brackets',
      primaryColor: '#EAB308',
    },
  },
  {
    id: 'pass-concert-festival',
    name: 'Electric Neon Music Fest',
    category: 'Event & Pass',
    description: 'Tiket festival musik dengan gradasi oranye matahari terbenam dan ungu neon.',
    layout: 'ticket-pass',
    dimensions: { width: 600, height: 900 },
    cardBg: '#180B26',
    cardBorder: { color: '#EC4899', width: 3.5, radius: 26 },
    cardShadow: { color: '#BE185D', offsetX: 7, offsetY: 7, blur: 0 },
    qrContainer: { bg: '#FFFFFF', border: '#F43F5E', borderWidth: 3, radius: 16, padding: 18, size: 380, yOffset: 260 },
    header: {
      badgeText: 'LIVE CONCERT TICKET',
      badgeBg: '#EC4899',
      badgeTextColor: '#FFFFFF',
      titleColor: '#FDF2F8',
      subtitleColor: '#F472B6',
      align: 'center',
    },
    footer: {
      ctaText: 'VALIDATE ENTRY CODE',
      ctaBg: '#EC4899',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 16,
      hintText: 'Valid for one entry per day with valid wristband',
      hintColor: '#FBCFE8',
    },
    decoration: {
      type: 'geometric-accents',
      primaryColor: '#EC4899',
      secondaryColor: '#A855F7',
    },
  },

  // =========================================================================
  // 10. MINIMAL & CLEAN THEMES
  // =========================================================================
  {
    id: 'minimal-swiss-white',
    name: 'Swiss Architectural Clean',
    category: 'Minimal',
    description: 'Desain tipografi Swiss dengan ruang negatif luas, garis 1px presisi, dan proporsi emas.',
    layout: 'minimal-clean',
    dimensions: { width: 640, height: 860 },
    cardBg: '#FFFFFF',
    cardBorder: { color: '#E2E8F0', width: 2, radius: 16 },
    cardShadow: { color: '#000000', offsetX: 0, offsetY: 4, blur: 16 },
    qrContainer: { bg: '#FFFFFF', border: '#F1F5F9', borderWidth: 1.5, radius: 12, padding: 20, size: 420 },
    header: {
      titleColor: '#0F172A',
      subtitleColor: '#64748B',
      align: 'center',
    },
    footer: {
      ctaText: 'Scan with Camera',
      ctaBg: '#0F172A',
      ctaTextColor: '#FFFFFF',
      ctaRadius: 25,
      hintText: 'Compatible with standard iOS & Android scanners',
      hintColor: '#94A3B8',
    },
    decoration: {
      type: 'none',
    },
  },
  {
    id: 'minimal-obsidian-black',
    name: 'Pure Obsidian Dark Minimal',
    category: 'Minimal',
    description: 'Kesederhanaan gelap murni dengan tipografi abu perak yang tenang.',
    layout: 'minimal-clean',
    dimensions: { width: 640, height: 860 },
    cardBg: '#0F172A',
    cardBorder: { color: '#1E293B', width: 2, radius: 18 },
    cardShadow: { color: '#000000', offsetX: 0, offsetY: 6, blur: 20 },
    qrContainer: { bg: '#FFFFFF', border: '#1E293B', borderWidth: 1.5, radius: 12, padding: 20, size: 420 },
    header: {
      titleColor: '#F8FAFC',
      subtitleColor: '#94A3B8',
      align: 'center',
    },
    footer: {
      ctaText: 'Scan to connect',
      ctaBg: '#F8FAFC',
      ctaTextColor: '#0F172A',
      ctaRadius: 25,
      hintText: 'Direct high speed encrypted link',
      hintColor: '#64748B',
    },
    decoration: {
      type: 'none',
    },
  },
];

// Helper to generate a complete catalog of 100+ themes programmatically
// by blending distinct colorways, geometries, borders, and aesthetics!
function generateFullThemeCatalog(): CardTheme[] {
  const catalog: CardTheme[] = [...CARD_THEMES];

  // Variations matrix
  const colorways = [
    { id: 'sunburst-yellow', name: 'Sunburst Gold', bg: '#FEF08A', primary: '#CA8A04', text: '#713F12', cat: 'Creative & Pop' as CardCategory },
    { id: 'vibrant-indigo', name: 'Deep Indigo Horizon', bg: '#EEF2FF', primary: '#4338CA', text: '#312E81', cat: 'Modern' as CardCategory },
    { id: 'candy-lavender', name: 'Lavender Mist Pop', bg: '#FAF5FF', primary: '#9333EA', text: '#581C87', cat: 'Pastel & Soft' as CardCategory },
    { id: 'crimson-fire', name: 'Crimson Flame Standee', bg: '#FEF2F2', primary: '#DC2626', text: '#991B1B', cat: 'Creative & Pop' as CardCategory },
    { id: 'arctic-ice', name: 'Arctic Ice Glaze', bg: '#F0F9FF', primary: '#0284C7', text: '#0C4A6E', cat: 'Minimal' as CardCategory },
    { id: 'emerald-mint', name: 'Fresh Mint Oasis', bg: '#ECFDF5', primary: '#059669', text: '#064E3B', cat: 'Pastel & Soft' as CardCategory },
    { id: 'peach-blush', name: 'Peach Velvet Glow', bg: '#FFF7ED', primary: '#EA580C', text: '#7C2D12', cat: 'Pastel & Soft' as CardCategory },
    { id: 'midnight-cyan', name: 'Midnight Deep Cyan', bg: '#082F49', primary: '#38BDF8', text: '#FFFFFF', cat: 'Dark & Neon' as CardCategory },
    { id: 'neon-violet', name: 'Electric Violet Glow', bg: '#2E1065', primary: '#C084FC', text: '#FFFFFF', cat: 'Dark & Neon' as CardCategory },
    { id: 'coffee-latte', name: 'Hazelnut Cream Brew', bg: '#FEF3C7', primary: '#B45309', text: '#78350F', cat: 'Restaurant & Cafe' as CardCategory },
    { id: 'nordic-granite', name: 'Nordic Granite Minimal', bg: '#F1F5F9', primary: '#334155', text: '#0F172A', cat: 'Minimal' as CardCategory },
    { id: 'tokyo-neon', name: 'Tokyo Shinjuku Pink', bg: '#18181B', primary: '#F43F5E', text: '#FFFFFF', cat: 'Dark & Neon' as CardCategory },
    { id: 'cyber-gold', name: 'Cybernetic Gold Matrix', bg: '#171717', primary: '#FBBF24', text: '#FFFFFF', cat: 'Tech & Cyber' as CardCategory },
    { id: 'bauhaus-primary', name: 'Bauhaus Primary Geometry', bg: '#FFFFFF', primary: '#DC2626', text: '#000000', cat: 'Abstract & Geometric' as CardCategory },
    { id: 'ocean-coral', name: 'Reef Coral & Aquamarine', bg: '#E0F2FE', primary: '#0284C7', text: '#0F172A', cat: 'Fluid & Organic' as CardCategory },
    { id: 'golden-amber', name: 'Imperial Amber Reserve', bg: '#FFFBEB', primary: '#D97706', text: '#451A03', cat: 'Luxury & Gold' as CardCategory },
  ];

  const layoutVariants: { layout: CardTheme['layout']; decoration: CardTheme['decoration']['type']; label: string }[] = [
    { layout: 'center-standard', decoration: 'corner-brackets', label: 'Payment Stand' },
    { layout: 'fluid-wave-bottom', decoration: 'waves-dual', label: 'Fluid Waves' },
    { layout: 'fluid-wave-top', decoration: 'waves-corner', label: 'Curved Ripple' },
    { layout: 'organic-blob', decoration: 'organic-blobs', label: 'Organic Blob' },
    { layout: 'badge-vertical', decoration: 'checkin-badge', label: 'Check-in Badge' },
    { layout: 'diagonal-split', decoration: 'diagonal-stripes', label: 'Angular Split' },
    { layout: 'brutalist-block', decoration: 'geometric-accents', label: 'Brutalist Block' },
  ];

  let idCounter = 1;
  for (const c of colorways) {
    for (const l of layoutVariants) {
      const themeId = `theme-${c.id}-${l.decoration}-${idCounter++}`;
      if (catalog.some((t) => t.id === themeId)) continue;

      const isDark = c.bg.startsWith('#0') || c.bg.startsWith('#1') || c.bg.startsWith('#2');
      const isSquare = l.layout === 'fluid-wave-bottom' || l.layout === 'organic-blob';
      const width = 640;
      const height = isSquare ? 640 : 880;

      catalog.push({
        id: themeId,
        name: `${c.name} ${l.label}`,
        category: c.cat,
        description: `Desain kartu ${l.label.toLowerCase()} dengan palet warna ${c.name.toLowerCase()} kontras tinggi.`,
        layout: l.layout,
        dimensions: { width, height },
        cardBg: c.bg,
        cardBorder: {
          color: isDark ? c.primary : '#000000',
          width: 3.5,
          radius: l.layout === 'brutalist-block' ? 0 : 26,
        },
        cardShadow: {
          color: isDark ? c.primary : '#000000',
          offsetX: 6,
          offsetY: 6,
          blur: isDark ? 10 : 0,
        },
        qrContainer: {
          bg: '#FFFFFF',
          border: isDark ? c.primary : '#000000',
          borderWidth: 3,
          radius: l.layout === 'brutalist-block' ? 0 : 18,
          padding: 16,
          size: isSquare ? 290 : 410,
          yOffset: isSquare ? 230 : undefined,
        },
        header: {
          badgeText: l.layout === 'badge-vertical' ? 'CHECK IN' : 'SCAN CODE',
          badgeBg: c.primary,
          badgeTextColor: '#FFFFFF',
          badgeBorderColor: isDark ? c.primary : '#000000',
          titleColor: c.text,
          subtitleColor: isDark ? '#94A3B8' : '#4B5563',
          align: 'center',
        },
        footer: {
          ctaText: 'SCAN HERE TO ACCESS',
          ctaBg: c.primary,
          ctaTextColor: '#FFFFFF',
          ctaBorderColor: isDark ? c.primary : '#000000',
          ctaRadius: l.layout === 'brutalist-block' ? 0 : 20,
          hintText: 'Arahkan kamera smartphone ke kode QR di atas',
          hintColor: isDark ? '#94A3B8' : '#475569',
          subText: 'FAST • SECURE • INSTANT CONNECTION',
          subTextColor: isDark ? '#64748B' : '#9CA3AF',
          showSecurityBadge: true,
        },
        decoration: {
          type: l.decoration,
          primaryColor: c.primary,
          secondaryColor: isDark ? '#38BDF8' : '#FBBF24',
          accentColor: '#FFFFFF',
          detailColor: c.primary,
        },
      });

      if (catalog.length >= 120) break;
    }
    if (catalog.length >= 120) break;
  }

  return catalog;
}

export const ALL_CARD_THEMES: CardTheme[] = generateFullThemeCatalog();

export function getCardThemeById(id: string): CardTheme {
  return ALL_CARD_THEMES.find((t) => t.id === id) || ALL_CARD_THEMES[0];
}

export function getCardThemesByCategory(category: CardCategory | 'All'): CardTheme[] {
  if (category === 'All') return ALL_CARD_THEMES;
  return ALL_CARD_THEMES.filter((t) => t.category === category);
}
