import { FontCategory, FontDefinition } from '@/types/qr';

export const FONT_CATEGORIES: FontCategory[] = [
  'Sans',
  'Serif',
  'Display',
  'Handwritten',
  'Elegant',
  'Modern',
  'Bold',
  'Futuristic',
  'Monospace',
  'Retro',
  'Casual',
];

export const FONT_DEFINITIONS: FontDefinition[] = [
  // 1. SANS
  { id: 'f-plus-jakarta', name: 'Plus Jakarta Sans', category: 'Sans', family: "'Plus Jakarta Sans', sans-serif" },
  { id: 'f-inter', name: 'Inter Tight', category: 'Sans', family: "'Inter', system-ui, sans-serif" },
  { id: 'f-outfit', name: 'Outfit', category: 'Sans', family: "'Outfit', sans-serif" },
  { id: 'f-dm-sans', name: 'DM Sans', category: 'Sans', family: "'DM Sans', sans-serif" },
  { id: 'f-work-sans', name: 'Work Sans', category: 'Sans', family: "'Work Sans', sans-serif" },
  { id: 'f-manrope', name: 'Manrope', category: 'Sans', family: "'Manrope', sans-serif" },
  { id: 'f-sora', name: 'Sora Clean', category: 'Sans', family: "'Sora', sans-serif" },
  { id: 'f-rubik', name: 'Rubik Geometric', category: 'Sans', family: "'Rubik', sans-serif" },
  { id: 'f-poppins', name: 'Poppins Rounded', category: 'Sans', family: "'Poppins', sans-serif" },
  { id: 'f-helvetica', name: 'Helvetica Classic', category: 'Sans', family: "'Helvetica Neue', Helvetica, Arial, sans-serif" },

  // 2. SERIF
  { id: 'f-playfair', name: 'Playfair Display', category: 'Serif', family: "'Playfair Display', serif" },
  { id: 'f-merriweather', name: 'Merriweather Book', category: 'Serif', family: "'Merriweather', serif" },
  { id: 'f-lora', name: 'Lora Editorial', category: 'Serif', family: "'Lora', serif" },
  { id: 'f-cormorant', name: 'Cormorant Garamond', category: 'Serif', family: "'Cormorant Garamond', serif" },
  { id: 'f-fraunces', name: 'Fraunces Oldstyle', category: 'Serif', family: "'Fraunces', serif" },
  { id: 'f-bodoni', name: 'Bodoni Moda', category: 'Serif', family: "'Bodoni Moda', serif" },
  { id: 'f-cinzel-serif', name: 'Cinzel Decorative', category: 'Serif', family: "'Cinzel', serif" },
  { id: 'f-baskerville', name: 'Libre Baskerville', category: 'Serif', family: "'Libre Baskerville', serif" },
  { id: 'f-prata', name: 'Prata Chic', category: 'Serif', family: "'Prata', serif" },
  { id: 'f-abril', name: 'Abril Fatface', category: 'Serif', family: "'Abril Fatface', serif" },

  // 3. DISPLAY
  { id: 'f-syne', name: 'Syne Neo-Brutalist', category: 'Display', family: "'Syne', sans-serif" },
  { id: 'f-archivo-black', name: 'Archivo Black Impact', category: 'Display', family: "'Archivo Black', sans-serif" },
  { id: 'f-cabinet', name: 'Cabinet Grotesk Ultra', category: 'Display', family: "'Cabinet Grotesk', sans-serif" },
  { id: 'f-bungee', name: 'Bungee Block', category: 'Display', family: "'Bungee', cursive" },
  { id: 'f-righteous', name: 'Righteous Wave', category: 'Display', family: "'Righteous', cursive" },
  { id: 'f-bebas', name: 'Bebas Neue Display', category: 'Display', family: "'Bebas Neue', sans-serif" },
  { id: 'f-monoton', name: 'Monoton Prismatic', category: 'Display', family: "'Monoton', cursive" },
  { id: 'f-clash', name: 'Clash Display Bold', category: 'Display', family: "'Clash Display', sans-serif" },
  { id: 'f-unbounded', name: 'Unbounded Wide', category: 'Display', family: "'Unbounded', sans-serif" },
  { id: 'f-chango', name: 'Chango Heavy', category: 'Display', family: "'Chango', cursive" },

  // 4. HANDWRITTEN
  { id: 'f-caveat', name: 'Caveat Casual Pen', category: 'Handwritten', family: "'Caveat', cursive" },
  { id: 'f-dancing', name: 'Dancing Script Flow', category: 'Handwritten', family: "'Dancing Script', cursive" },
  { id: 'f-pacifico', name: 'Pacifico Brush', category: 'Handwritten', family: "'Pacifico', cursive" },
  { id: 'f-sacramento', name: 'Sacramento Delicate', category: 'Handwritten', family: "'Sacramento', cursive" },
  { id: 'f-kalam', name: 'Kalam Felt Marker', category: 'Handwritten', family: "'Kalam', cursive" },
  { id: 'f-great-vibes', name: 'Great Vibes Signature', category: 'Handwritten', family: "'Great Vibes', cursive" },
  { id: 'f-shadows', name: 'Shadows Into Light', category: 'Handwritten', family: "'Shadows Into Light', cursive" },
  { id: 'f-satisfy', name: 'Satisfy Smooth', category: 'Handwritten', family: "'Satisfy', cursive" },
  { id: 'f-amatic', name: 'Amatic Tall Pen', category: 'Handwritten', family: "'Amatic SC', cursive" },
  { id: 'f-cookie', name: 'Cookie Retro Script', category: 'Handwritten', family: "'Cookie', cursive" },

  // 5. ELEGANT
  { id: 'f-cinzel', name: 'Cinzel Royal', category: 'Elegant', family: "'Cinzel', serif" },
  { id: 'f-marcellus', name: 'Marcellus Roman', category: 'Elegant', family: "'Marcellus', serif" },
  { id: 'f-alex-brush', name: 'Alex Brush Haute', category: 'Elegant', family: "'Alex Brush', cursive" },
  { id: 'f-tenor', name: 'Tenor Sans Minimal', category: 'Elegant', family: "'Tenor Sans', sans-serif" },
  { id: 'f-italiana', name: 'Italiana Couture', category: 'Elegant', family: "'Italiana', serif" },
  { id: 'f-castoro', name: 'Castoro Titling', category: 'Elegant', family: "'Castoro Titling', serif" },
  { id: 'f-allura', name: 'Allura Script', category: 'Elegant', family: "'Allura', cursive" },
  { id: 'f-playfair-sc', name: 'Playfair Small Caps', category: 'Elegant', family: "'Playfair Display SC', serif" },
  { id: 'f-forum', name: 'Forum Classical', category: 'Elegant', family: "'Forum', serif" },
  { id: 'f-el-messiri', name: 'El Messiri Curved', category: 'Elegant', family: "'El Messiri', sans-serif" },

  // 6. MODERN
  { id: 'f-space-grotesk', name: 'Space Grotesk Modern', category: 'Modern', family: "'Space Grotesk', sans-serif" },
  { id: 'f-clash-grotesk', name: 'Clash Grotesk Clean', category: 'Modern', family: "'Clash Grotesk', sans-serif" },
  { id: 'f-general-sans', name: 'General Sans Neutral', category: 'Modern', family: "'General Sans', sans-serif" },
  { id: 'f-satoshi', name: 'Satoshi Sharp', category: 'Modern', family: "'Satoshi', sans-serif" },
  { id: 'f-switzer', name: 'Switzer Swiss', category: 'Modern', family: "'Switzer', sans-serif" },
  { id: 'f-ranade', name: 'Ranade Clean', category: 'Modern', family: "'Ranade', sans-serif" },
  { id: 'f-cabinet-condensed', name: 'Cabinet Compact', category: 'Modern', family: "'Cabinet Grotesk', sans-serif" },
  { id: 'f-epilogue', name: 'Epilogue Editorial', category: 'Modern', family: "'Epilogue', sans-serif" },
  { id: 'f-figtree', name: 'Figtree Product', category: 'Modern', family: "'Figtree', sans-serif" },
  { id: 'f-lexend', name: 'Lexend High Readability', category: 'Modern', family: "'Lexend', sans-serif" },

  // 7. BOLD
  { id: 'f-black-ops', name: 'Black Ops Heavy', category: 'Bold', family: "'Black Ops One', cursive" },
  { id: 'f-impact', name: 'Impact Brutalist', category: 'Bold', family: "'Impact', 'Arial Black', sans-serif" },
  { id: 'f-paytone', name: 'Paytone Sturdy One', category: 'Bold', family: "'Paytone One', sans-serif" },
  { id: 'f-titan', name: 'Titan Solid', category: 'Bold', family: "'Titan One', cursive" },
  { id: 'f-alfa-slab', name: 'Alfa Slab Heavy', category: 'Bold', family: "'Alfa Slab One', cursive" },
  { id: 'f-bowlby', name: 'Bowlby One Heavy', category: 'Bold', family: "'Bowlby One', cursive" },
  { id: 'f-passion', name: 'Passion One Thick', category: 'Bold', family: "'Passion One', cursive" },
  { id: 'f-secular', name: 'Secular Solid Block', category: 'Bold', family: "'Secular One', sans-serif" },
  { id: 'f-fugaz', name: 'Fugaz One Dynamic', category: 'Bold', family: "'Fugaz One', cursive" },
  { id: 'f-chango-bold', name: 'Chango Poster Bold', category: 'Bold', family: "'Chango', cursive" },

  // 8. FUTURISTIC
  { id: 'f-orbitron', name: 'Orbitron Sci-Fi', category: 'Futuristic', family: "'Orbitron', sans-serif" },
  { id: 'f-audiowide', name: 'Audiowide Synth', category: 'Futuristic', family: "'Audiowide', cursive" },
  { id: 'f-exo', name: 'Exo Cyberpunk 2', category: 'Futuristic', family: "'Exo 2', sans-serif" },
  { id: 'f-chakra', name: 'Chakra Petch Mecha', category: 'Futuristic', family: "'Chakra Petch', sans-serif" },
  { id: 'f-michroma', name: 'Michroma Aerospace', category: 'Futuristic', family: "'Michroma', sans-serif" },
  { id: 'f-rajdhani', name: 'Rajdhani Tactical', category: 'Futuristic', family: "'Rajdhani', sans-serif" },
  { id: 'f-teko', name: 'Teko Condensed Mecha', category: 'Futuristic', family: "'Teko', sans-serif" },
  { id: 'f-electrolize', name: 'Electrolize Electronic', category: 'Futuristic', family: "'Electrolize', sans-serif" },
  { id: 'f-saira', name: 'Saira Stencil Cyber', category: 'Futuristic', family: "'Saira Stencil One', cursive" },
  { id: 'f-russo', name: 'Russo Heavy Space', category: 'Futuristic', family: "'Russo One', sans-serif" },

  // 9. MONOSPACE
  { id: 'f-space-mono', name: 'Space Mono Developer', category: 'Monospace', family: "'Space Mono', monospace" },
  { id: 'f-fira-code', name: 'Fira Code Terminal', category: 'Monospace', family: "'Fira Code', monospace" },
  { id: 'f-jetbrains', name: 'JetBrains Code Pro', category: 'Monospace', family: "'JetBrains Mono', monospace" },
  { id: 'f-ibm-plex-mono', name: 'IBM Plex Industrial Mono', category: 'Monospace', family: "'IBM Plex Mono', monospace" },
  { id: 'f-inconsolata', name: 'Inconsolata Clean', category: 'Monospace', family: "'Inconsolata', monospace" },
  { id: 'f-vt323', name: 'VT323 Retro Terminal', category: 'Monospace', family: "'VT323', monospace" },
  { id: 'f-press-start', name: 'Press Start 8-Bit', category: 'Monospace', family: "'Press Start 2P', monospace" },
  { id: 'f-courier-prime', name: 'Courier Screenplay', category: 'Monospace', family: "'Courier Prime', monospace" },
  { id: 'f-share-tech-mono', name: 'Share Tech Radar', category: 'Monospace', family: "'Share Tech Mono', monospace" },
  { id: 'f-dm-mono', name: 'DM Mono Crisp', category: 'Monospace', family: "'DM Mono', monospace" },

  // 10. RETRO
  { id: 'f-shrikhand', name: 'Shrikhand 70s Psychedelic', category: 'Retro', family: "'Shrikhand', cursive" },
  { id: 'f-lobster', name: 'Lobster Vintage Diner', category: 'Retro', family: "'Lobster', cursive" },
  { id: 'f-faster-one', name: 'Faster 60s Speed', category: 'Retro', family: "'Faster One', cursive" },
  { id: 'f-major-mono', name: 'Major Mono 1980', category: 'Retro', family: "'Major Mono Display', monospace" },
  { id: 'f-bungee-shade', name: 'Bungee Arcade Shade', category: 'Retro', family: "'Bungee Shade', cursive" },
  { id: 'f-limelight', name: 'Limelight 1920 Deco', category: 'Retro', family: "'Limelight', cursive" },
  { id: 'f-poiret', name: 'Poiret Art Deco One', category: 'Retro', family: "'Poiret One', cursive" },
  { id: 'f-nostalgia', name: 'Nostalgia Groovy 70s', category: 'Retro', family: "'Bungee Inline', cursive" },
  { id: 'f-rye', name: 'Rye Wild West', category: 'Retro', family: "'Rye', cursive" },
  { id: 'f-ultra', name: 'Ultra Poster Woodcut', category: 'Retro', family: "'Ultra', serif" },

  // 11. CASUAL
  { id: 'f-sniglet', name: 'Sniglet Friendly Comic', category: 'Casual', family: "'Sniglet', cursive" },
  { id: 'f-fredoka', name: 'Fredoka Rounded Pop', category: 'Casual', family: "'Fredoka', sans-serif" },
  { id: 'f-comfortaa', name: 'Comfortaa Organic', category: 'Casual', family: "'Comfortaa', cursive" },
  { id: 'f-quicksand', name: 'Quicksand Modern Clean', category: 'Casual', family: "'Quicksand', sans-serif" },
  { id: 'f-nunito', name: 'Nunito Friendly Soft', category: 'Casual', family: "'Nunito', sans-serif" },
  { id: 'f-varela', name: 'Varela Round Smooth', category: 'Casual', family: "'Varela Round', sans-serif" },
  { id: 'f-boogaloo', name: 'Boogaloo Jazzy', category: 'Casual', family: "'Boogaloo', cursive" },
  { id: 'f-chewy', name: 'Chewy Bubble Snack', category: 'Casual', family: "'Chewy', cursive" },
  { id: 'f-gochi', name: 'Gochi Hand Scribble', category: 'Casual', family: "'Gochi Hand', cursive" },
  { id: 'f-patrick', name: 'Patrick Hand Classroom', category: 'Casual', family: "'Patrick Hand', cursive" },
];
