import { FramePreset } from '@/types/qr';

export const FRAME_CATEGORIES = [
  'All',
  'Popular',
  'Call to Action',
  'Brutalist',
  'Badges',
  'Retail & Menu',
  'Social',
  'Cards',
  'Events',
  'Minimal',
] as const;

export const FRAME_PRESETS: FramePreset[] = [
  // 1. POPULAR
  {
    id: 'frame-scan-me-bottom',
    name: 'SCAN ME Pill Banner',
    category: 'Popular',
    text: 'SCAN ME',
    subtext: 'POINT CAMERA HERE',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#000000',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'QrCode',
  },
  {
    id: 'frame-scan-here-badge',
    name: 'SCAN HERE Classic Badge',
    category: 'Popular',
    text: 'SCAN HERE',
    subtext: 'INSTANT ACCESS',
    position: 'top',
    style: 'solid-badge',
    textColor: '#000000',
    backgroundColor: '#FFE600',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Camera',
  },
  {
    id: 'frame-tap-to-scan',
    name: 'TAP TO SCAN Brutalist Box',
    category: 'Popular',
    text: 'TAP TO SCAN',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#70EE9C',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Hand',
  },
  {
    id: 'frame-open-link',
    name: 'OPEN LINK Pill',
    category: 'Popular',
    text: 'OPEN LINK',
    subtext: 'FAST BROWSER REDIRECT',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#0066FF',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'ExternalLink',
  },
  {
    id: 'frame-polaroid-vintage',
    name: 'Polaroid Snapshot',
    category: 'Popular',
    text: 'POINT & SCAN',
    subtext: 'PHOTO MEMORY',
    position: 'polaroid',
    style: 'polaroid-card',
    textColor: '#18181B',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Sparkles',
  },

  // 2. CALL TO ACTION
  {
    id: 'frame-scan-now-urgent',
    name: 'SCAN NOW Alert',
    category: 'Call to Action',
    text: 'SCAN NOW!',
    subtext: 'LIMITED TIME ONLY',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#FFFFFF',
    backgroundColor: '#EF4444',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Zap',
  },
  {
    id: 'frame-visit-us',
    name: 'VISIT OUR WEBSITE',
    category: 'Call to Action',
    text: 'VISIT US',
    subtext: 'WWW.EXAMPLE.COM',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#1E1B4B',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Globe',
  },
  {
    id: 'frame-get-started',
    name: 'GET STARTED',
    category: 'Call to Action',
    text: 'GET STARTED',
    subtext: 'FREE REGISTRATION',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#000000',
    backgroundColor: '#FFE600',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'ArrowRight',
  },
  {
    id: 'frame-explore-more',
    name: 'EXPLORE MORE',
    category: 'Call to Action',
    text: 'EXPLORE MORE',
    subtext: 'DISCOVER COLLECTION',
    position: 'bottom',
    style: 'banner',
    textColor: '#FFFFFF',
    backgroundColor: '#0F766E',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Compass',
  },
  {
    id: 'frame-claim-offer',
    name: 'CLAIM EXCLUSIVE OFFER',
    category: 'Call to Action',
    text: 'CLAIM OFFER',
    subtext: 'TAP OR SCAN',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#F97316',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Gift',
  },

  // 3. BRUTALIST
  {
    id: 'frame-brut-caution',
    name: 'CAUTION // HIGH DATA',
    category: 'Brutalist',
    text: 'WARNING: SCANNABLE',
    subtext: 'DO NOT COVER CORNERS',
    position: 'brutalist',
    style: 'brutalist-hazard',
    textColor: '#000000',
    backgroundColor: '#FFE600',
    borderColor: '#000000',
    borderWidth: 4,
    badgeIcon: 'AlertTriangle',
  },
  {
    id: 'frame-brut-mono-block',
    name: 'MONO PROTOCOL // 01',
    category: 'Brutalist',
    text: 'PROTOCOL [SCAN]',
    subtext: 'DEVICE READY',
    position: 'top',
    style: 'brutalist-block',
    textColor: '#FFFFFF',
    backgroundColor: '#000000',
    borderColor: '#000000',
    borderWidth: 4,
    badgeIcon: 'Terminal',
  },
  {
    id: 'frame-brut-acid-tag',
    name: 'ACID INDUSTRIAL TAG',
    category: 'Brutalist',
    text: 'QUICK SCAN // VERIFIED',
    subtext: 'SECURE OPTICAL LINK',
    position: 'tag',
    style: 'brutalist-tag',
    textColor: '#000000',
    backgroundColor: '#A3E635',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Tag',
  },
  {
    id: 'frame-brut-electric-pink',
    name: 'RAW POP PUNCH',
    category: 'Brutalist',
    text: 'OPTICAL PAYLOAD',
    subtext: '100% UNCOMPRESSED',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#FF5E5B',
    borderColor: '#000000',
    borderWidth: 4,
    badgeIcon: 'Cpu',
  },
  {
    id: 'frame-brut-cyan-edge',
    name: 'CYAN OVERLOAD',
    category: 'Brutalist',
    text: 'INPUT SIGNAL',
    subtext: 'READINESS 100%',
    position: 'box',
    style: 'brutalist-box',
    textColor: '#000000',
    backgroundColor: '#38BDF8',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Radio',
  },

  // 4. BADGES
  {
    id: 'frame-badge-vip',
    name: 'VIP ALL-ACCESS',
    category: 'Badges',
    text: 'VIP ACCESS PASS',
    subtext: 'PRIORITY ENTRY',
    position: 'top',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#4C1D95',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Crown',
  },
  {
    id: 'frame-badge-verified',
    name: 'OFFICIALLY VERIFIED',
    category: 'Badges',
    text: 'VERIFIED QR',
    subtext: 'AUTHENTICATED CODE',
    position: 'badge',
    style: 'circular-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#0284C7',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'CheckCircle2',
  },
  {
    id: 'frame-badge-eco',
    name: '100% PAPERLESS',
    category: 'Badges',
    text: 'GO PAPERLESS',
    subtext: 'ECO FRIENDLY SCAN',
    position: 'top',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#15803D',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Leaf',
  },
  {
    id: 'frame-badge-award',
    name: 'GOLD MEDAL QUALITY',
    category: 'Badges',
    text: 'AWARD WINNING',
    subtext: 'GOLD STANDARD',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#000000',
    backgroundColor: '#FACC15',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Award',
  },
  {
    id: 'frame-badge-shield',
    name: 'SECURE ENCRYPTED',
    category: 'Badges',
    text: 'SECURE LINK',
    subtext: 'SSL 256-BIT',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#0F172A',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'ShieldCheck',
  },

  // 5. RETAIL & MENU
  {
    id: 'frame-menu-restaurant',
    name: 'VIEW OUR DIGITAL MENU',
    category: 'Retail & Menu',
    text: 'VIEW MENU',
    subtext: 'FOOD & DRINKS',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#B45309',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Utensils',
  },
  {
    id: 'frame-pay-here',
    name: 'TOUCHLESS PAYMENT',
    category: 'Retail & Menu',
    text: 'PAY HERE',
    subtext: 'FAST CONTACTLESS CHECKOUT',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#4ADE80',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'CreditCard',
  },
  {
    id: 'frame-table-order',
    name: 'ORDER FROM TABLE',
    category: 'Retail & Menu',
    text: 'ORDER HERE',
    subtext: 'TABLE SERVICE',
    position: 'top',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#BE123C',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Coffee',
  },
  {
    id: 'frame-discount-coupon',
    name: 'SCAN FOR 20% OFF',
    category: 'Retail & Menu',
    text: 'GET 20% OFF',
    subtext: 'REDEEM AT CASHIER',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#FFFFFF',
    backgroundColor: '#DC2626',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Percent',
  },
  {
    id: 'frame-review-feedback',
    name: 'RATE YOUR EXPERIENCE',
    category: 'Retail & Menu',
    text: 'LEAVE A REVIEW',
    subtext: 'WE VALUE YOUR FEEDBACK',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#000000',
    backgroundColor: '#FDE047',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Star',
  },

  // 6. SOCIAL & CONNECT
  {
    id: 'frame-social-instagram',
    name: 'FOLLOW ON INSTAGRAM',
    category: 'Social',
    text: 'FOLLOW US',
    subtext: '@OUR_BRAND',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#BE185D',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Instagram',
  },
  {
    id: 'frame-social-whatsapp',
    name: 'CHAT ON WHATSAPP',
    category: 'Social',
    text: 'CHAT WITH US',
    subtext: 'DIRECT SUPPORT',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#FFFFFF',
    backgroundColor: '#16A34A',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'MessageCircle',
  },
  {
    id: 'frame-social-community',
    name: 'JOIN DISCORD COMMUNITY',
    category: 'Social',
    text: 'JOIN COMMUNITY',
    subtext: 'CHAT & CHILL',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#FFFFFF',
    backgroundColor: '#4F46E5',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Users',
  },
  {
    id: 'frame-social-connect',
    name: 'SAVE MY CONTACT',
    category: 'Social',
    text: 'SAVE CONTACT',
    subtext: 'VCARD 1-TAP SYNC',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#000000',
    backgroundColor: '#67E8F9',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'UserPlus',
  },
  {
    id: 'frame-social-youtube',
    name: 'WATCH ON YOUTUBE',
    category: 'Social',
    text: 'WATCH VIDEO',
    subtext: 'NEW EPISODE OUT NOW',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#DC2626',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Play',
  },

  // 7. CARDS & TICKETS
  {
    id: 'frame-event-ticket',
    name: 'ADMIT ONE TICKET',
    category: 'Cards',
    text: 'ADMIT ONE',
    subtext: 'SECTION A // SEAT 42',
    position: 'box',
    style: 'ticket-perforated',
    textColor: '#000000',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Ticket',
  },
  {
    id: 'frame-boarding-pass',
    name: 'BOARDING PASS',
    category: 'Cards',
    text: 'GATE 07 // PRIORITY',
    subtext: 'SHOW TO ATTENDANT',
    position: 'top',
    style: 'brutalist-block',
    textColor: '#FFFFFF',
    backgroundColor: '#0284C7',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Plane',
  },
  {
    id: 'frame-modern-id-badge',
    name: 'EMPLOYEE ID BADGE',
    category: 'Cards',
    text: 'AUTHORIZED PERSONNEL',
    subtext: 'TAP OR SCAN BADGE',
    position: 'top',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#1E293B',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'BadgeCheck',
  },
  {
    id: 'frame-membership-card',
    name: 'VIP CLUB MEMBER',
    category: 'Cards',
    text: 'MEMBER CARD',
    subtext: 'VALID THRU 2028',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#000000',
    backgroundColor: '#FDE047',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Sparkles',
  },
  {
    id: 'frame-hotel-keycard',
    name: 'DIGITAL ROOM ACCESS',
    category: 'Cards',
    text: 'ROOM ACCESS',
    subtext: 'SCAN TO UNLOCK',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#4338CA',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Key',
  },

  // 8. EVENTS & WIFI
  {
    id: 'frame-wifi-connect',
    name: 'FREE GUEST WI-FI',
    category: 'Events',
    text: 'CONNECT TO WI-FI',
    subtext: 'NO PASSWORD TYPING',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#0284C7',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Wifi',
  },
  {
    id: 'frame-event-checkin',
    name: 'EXPRESS EVENT CHECK-IN',
    category: 'Events',
    text: 'EXPRESS CHECK-IN',
    subtext: 'SPEED SCAN AT ENTRANCE',
    position: 'top',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#FFE600',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'CheckCheck',
  },
  {
    id: 'frame-wedding-rsvp',
    name: 'WEDDING RSVP',
    category: 'Events',
    text: 'PLEASE RSVP',
    subtext: 'SAVE THE DATE',
    position: 'bottom',
    style: 'pill-banner',
    textColor: '#4C0519',
    backgroundColor: '#FFE4E6',
    borderColor: '#4C0519',
    borderWidth: 2,
    badgeIcon: 'Heart',
  },
  {
    id: 'frame-conference-agenda',
    name: 'CONFERENCE SCHEDULE',
    category: 'Events',
    text: 'VIEW AGENDA',
    subtext: 'LIVE SPEAKER TIMETABLE',
    position: 'bottom',
    style: 'solid-badge',
    textColor: '#FFFFFF',
    backgroundColor: '#1E1B4B',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Calendar',
  },
  {
    id: 'frame-booth-contest',
    name: 'ENTER BOOTH GIVEAWAY',
    category: 'Events',
    text: 'WIN PRIZES',
    subtext: 'SPIN & WIN TODAY',
    position: 'bottom',
    style: 'brutalist-block',
    textColor: '#000000',
    backgroundColor: '#FB923C',
    borderColor: '#000000',
    borderWidth: 3,
    badgeIcon: 'Gift',
  },

  // 9. MINIMAL
  {
    id: 'frame-minimal-underline',
    name: 'Underline Scan',
    category: 'Minimal',
    text: 'SCAN',
    position: 'bottom',
    style: 'minimal-bar',
    textColor: '#000000',
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 2,
    badgeIcon: 'Scan',
  },
  {
    id: 'frame-minimal-topbar',
    name: 'Minimal Header Tag',
    category: 'Minimal',
    text: 'SCAN CODE',
    position: 'top',
    style: 'minimal-bar',
    textColor: '#374151',
    backgroundColor: '#F3F4F6',
    borderColor: '#D1D5DB',
    borderWidth: 2,
    badgeIcon: 'QrCode',
  },
  {
    id: 'frame-minimal-borderless',
    name: 'Clean Floating Label',
    category: 'Minimal',
    text: 'POINT CAMERA',
    position: 'bottom',
    style: 'minimal-bar',
    textColor: '#6B7280',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderWidth: 0,
  },
];

// Dynamically generate extra diverse variations to exceed 100+ frames
const ACTION_VERBS = [
  { text: 'DOWNLOAD APP', sub: 'iOS & Android Free', bg: '#000000', fg: '#FFFFFF', cat: 'Call to Action' },
  { text: 'LISTEN ON SPOTIFY', sub: 'New Album Stream', bg: '#1DB954', fg: '#000000', cat: 'Social' },
  { text: 'BOOK APPOINTMENT', sub: 'Instant Calendar', bg: '#0284C7', fg: '#FFFFFF', cat: 'Call to Action' },
  { text: 'READ ARTICLE', sub: 'Full Story Online', bg: '#475569', fg: '#FFFFFF', cat: 'Minimal' },
  { text: 'DONATE HERE', sub: 'Support Our Cause', bg: '#BE123C', fg: '#FFFFFF', cat: 'Call to Action' },
  { text: 'GET DIRECTIONS', sub: 'Open Google Maps', bg: '#16A34A', fg: '#FFFFFF', cat: 'Events' },
  { text: 'TIKTOK TREND', sub: 'Follow @channel', bg: '#000000', fg: '#FFFFFF', cat: 'Social' },
  { text: 'ORDER CATALOG', sub: 'Autumn 2028 Edition', bg: '#B45309', fg: '#FFFFFF', cat: 'Retail & Menu' },
  { text: 'REGISTER VEHICLE', sub: 'Fast Pass Parking', bg: '#1E293B', fg: '#FFFFFF', cat: 'Cards' },
  { text: 'WIFI 5G HIGH-SPEED', sub: 'Guest Access Network', bg: '#7C3AED', fg: '#FFFFFF', cat: 'Events' },
  { text: 'SECRET DISCOUNT', sub: 'VIP Mystery Box', bg: '#FFE600', fg: '#000000', cat: 'Brutalist' },
  { text: 'STREAM PODCAST', sub: 'Listen to Episode 89', bg: '#0F172A', fg: '#FFFFFF', cat: 'Social' },
  { text: 'MUSEUM AUDIO GUIDE', sub: 'Exhibit #42 Commentary', bg: '#78350F', fg: '#FFFFFF', cat: 'Events' },
  { text: 'GYM CHECK-IN', sub: 'Member Access QR', bg: '#DC2626', fg: '#FFFFFF', cat: 'Cards' },
  { text: 'CONTACTLESS VALET', sub: 'Request Vehicle Pickup', bg: '#334155', fg: '#FFFFFF', cat: 'Retail & Menu' },
  { text: 'BUY TICKETS NOW', sub: 'Doors Open at 8 PM', bg: '#FF5E5B', fg: '#000000', cat: 'Brutalist' },
];

ACTION_VERBS.forEach((item, index) => {
  FRAME_PRESETS.push({
    id: `extra-frame-${index + 1}`,
    name: item.text,
    category: item.cat as any,
    text: item.text,
    subtext: item.sub,
    position: index % 2 === 0 ? 'bottom' : 'top',
    style: index % 3 === 0 ? 'brutalist-block' : index % 3 === 1 ? 'pill-banner' : 'solid-badge',
    textColor: item.fg,
    backgroundColor: item.bg,
    borderColor: '#000000',
    borderWidth: 3,
  });
});
