import { StyleCategory, StylePreset } from '@/types/qr';

export const STYLE_CATEGORIES: StyleCategory[] = [
  'Minimal',
  'Modern',
  'Classic',
  'Rounded',
  'Dot',
  'Pixel',
  'Diamond',
  'Star',
  'Soft',
  'Bold',
  'Luxury',
  'Corporate',
  'Glass',
  'Neon',
  'Futuristic',
  'Gaming',
  'Cute',
  'Elegant',
  'Retro',
  'Gradient',
  'Tech',
  'Geometric',
];

export const STYLE_PRESETS: StylePreset[] = [
  // 1. MINIMAL
  {
    id: 'min-clean-black',
    name: 'Clean Charcoal',
    category: 'Minimal',
    description: 'Crisp minimal aesthetic with pure monochrome lines',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#111827',
      background: '#FFFFFF',
    },
  },
  {
    id: 'min-nordic-slate',
    name: 'Nordic Slate',
    category: 'Minimal',
    description: 'Subtle slate gray on cool off-white',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'rounded',
      foreground: '#334155',
      background: '#F8FAFC',
    },
  },
  {
    id: 'min-paper-ink',
    name: 'Paper & Ink',
    category: 'Minimal',
    description: 'Warm newsprint off-white with deep ink tones',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#1C1917',
      background: '#FAFAF9',
    },
  },
  {
    id: 'min-ghost-mono',
    name: 'Ghost Mono',
    category: 'Minimal',
    description: 'High minimalism with rounded dots and soft spacing',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#0F172A',
      background: '#FFFFFF',
    },
  },
  {
    id: 'min-brut-mono',
    name: 'Brut Minimal',
    category: 'Minimal',
    description: 'Stark sharp geometry for brutalist brands',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#FFFFFF',
    },
  },

  // 2. MODERN
  {
    id: 'mod-neo-indigo',
    name: 'Neo Indigo',
    category: 'Modern',
    description: 'Sleek dark indigo on clean white with squircle corners',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#1E1B4B',
      background: '#FFFFFF',
    },
  },
  {
    id: 'mod-electric-blue',
    name: 'Electric Cobalt',
    category: 'Modern',
    description: 'Vibrant punchy blue with high contrast finish',
    config: {
      dotStyle: 'classy-rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'dot',
      foreground: '#0047FF',
      background: '#FFFFFF',
    },
  },
  {
    id: 'mod-emerald-pulse',
    name: 'Emerald Shift',
    category: 'Modern',
    description: 'Modern botanical emerald with rounded modules',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#064E3B',
      background: '#F0FDF4',
    },
  },
  {
    id: 'mod-crimson-edge',
    name: 'Crimson Edge',
    category: 'Modern',
    description: 'Bold red foreground on crisp light silver',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'square',
      foreground: '#991B1B',
      background: '#F8FAFC',
    },
  },
  {
    id: 'mod-carbon-teal',
    name: 'Carbon Teal',
    category: 'Modern',
    description: 'High-tech deep teal with rounded finder pattern',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#115E59',
      background: '#F0FDFA',
    },
  },

  // 3. CLASSIC
  {
    id: 'cls-standard-qr',
    name: 'Standard Heritage',
    category: 'Classic',
    description: 'Pure canonical QR design for universal industrial scan',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#FFFFFF',
    },
  },
  {
    id: 'cls-navy-seal',
    name: 'Navy Seal',
    category: 'Classic',
    description: 'Formal corporate dark navy for diplomas & stationery',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#FFFFFF',
    },
  },
  {
    id: 'cls-bordeaux',
    name: 'Classic Bordeaux',
    category: 'Classic',
    description: 'Deep wine burgundy for restaurants and vineyards',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'square',
      foreground: '#4C0519',
      background: '#FFF1F2',
    },
  },
  {
    id: 'cls-forest-hall',
    name: 'Forest Heritage',
    category: 'Classic',
    description: 'Prestigious racing green with double border',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'rounded',
      foreground: '#064E3B',
      background: '#FDFBF7',
    },
  },
  {
    id: 'cls-espresso',
    name: 'Classic Espresso',
    category: 'Classic',
    description: 'Rich dark roast brown with crisp contrast',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#29180E',
      background: '#FDFBF7',
    },
  },

  // 4. ROUNDED
  {
    id: 'rnd-pebble',
    name: 'Pebble Soft',
    category: 'Rounded',
    description: 'Soft organic pebble shapes for friendly mobile apps',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'rounded',
      foreground: '#1E293B',
      background: '#F8FAFC',
    },
  },
  {
    id: 'rnd-smooth-coral',
    name: 'Smooth Coral',
    category: 'Rounded',
    description: 'Gentle coral tones with rounded elements',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#BE123C',
      background: '#FFF1F2',
    },
  },
  {
    id: 'rnd-bubblegum',
    name: 'Bubblegum Round',
    category: 'Rounded',
    description: 'Playful pink circles on sweet white',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'dot',
      foreground: '#9D174D',
      background: '#FDF2F8',
    },
  },
  {
    id: 'rnd-ocean-wave',
    name: 'Ocean Wave',
    category: 'Rounded',
    description: 'Rounded sky blue dots with squircle outer anchors',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#0369A1',
      background: '#F0F9FF',
    },
  },
  {
    id: 'rnd-clay',
    name: 'Terracotta Clay',
    category: 'Rounded',
    description: 'Earthy warm terracotta with rounded curves',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#9A3412',
      background: '#FFF7ED',
    },
  },

  // 5. DOT
  {
    id: 'dot-matrix-black',
    name: 'Black Dot Matrix',
    category: 'Dot',
    description: 'Pure circular dot matrix with circular eyes',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'dot',
      cornerDotStyle: 'dot',
      foreground: '#111827',
      background: '#FFFFFF',
    },
  },
  {
    id: 'dot-cyan-sonar',
    name: 'Cyan Sonar',
    category: 'Dot',
    description: 'Deep cyan point cloud style',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'dot',
      foreground: '#0E7490',
      background: '#ECFEFF',
    },
  },
  {
    id: 'dot-violet-galaxy',
    name: 'Violet Galaxy',
    category: 'Dot',
    description: 'Rich royal purple dots on lilac blush',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'dot',
      cornerDotStyle: 'dot',
      foreground: '#581C87',
      background: '#FAF5FF',
    },
  },
  {
    id: 'dot-amber-glow',
    name: 'Amber Array',
    category: 'Dot',
    description: 'Warm amber points on light cream background',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#B45309',
      background: '#FFFBEB',
    },
  },
  {
    id: 'dot-graphite',
    name: 'Graphite Dots',
    category: 'Dot',
    description: 'Industrial charcoal dots on light cool gray',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#374151',
      background: '#F9FAFB',
    },
  },

  // 6. PIXEL
  {
    id: 'px-arcade-8bit',
    name: 'Arcade 8-Bit',
    category: 'Pixel',
    description: 'Chunky retro 8-bit arcade pixels with bold square frame',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#1E1B4B',
      background: '#FFFFFF',
    },
  },
  {
    id: 'px-gameboy-green',
    name: 'Classic Handheld',
    category: 'Pixel',
    description: 'Nostalgic LCD olive and dark pixel matrix',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#142814',
      background: '#8BAC0F',
    },
  },
  {
    id: 'px-cyber-ruby',
    name: 'Cyber Ruby Pixel',
    category: 'Pixel',
    description: 'Sharp pixelated ruby red on crisp white',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#881337',
      background: '#FFF1F2',
    },
  },
  {
    id: 'px-dungeon-slate',
    name: 'Dungeon Slate',
    category: 'Pixel',
    description: 'Dark gaming pixel theme for gamer tags and discord',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#E2E8F0',
    },
  },
  {
    id: 'px-electric-lemon',
    name: 'Retro Voltage',
    category: 'Pixel',
    description: 'High contrast black on neon yellow pixel style',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#FFE600',
    },
  },

  // 7. DIAMOND
  {
    id: 'dia-rhombus-black',
    name: 'Rhombus Luxury',
    category: 'Diamond',
    description: 'Sharp rotated diamond cells for jewelry and fashion',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'diamond',
      foreground: '#18181B',
      background: '#FFFFFF',
    },
  },
  {
    id: 'dia-sapphire-gem',
    name: 'Sapphire Gem',
    category: 'Diamond',
    description: 'Glittering royal blue diamond pattern',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'diamond',
      foreground: '#1D4ED8',
      background: '#EFF6FF',
    },
  },
  {
    id: 'dia-emerald-cut',
    name: 'Emerald Cut',
    category: 'Diamond',
    description: 'Jeweler emerald tones with diamond finder centers',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'diamond',
      foreground: '#047857',
      background: '#ECFDF5',
    },
  },
  {
    id: 'dia-amethyst-facet',
    name: 'Amethyst Facet',
    category: 'Diamond',
    description: 'Deep purple gemstone facets with high scan reliability',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'diamond',
      foreground: '#6B21A8',
      background: '#FAF5FF',
    },
  },
  {
    id: 'dia-golden-carat',
    name: 'Golden Carat',
    category: 'Diamond',
    description: 'Rich dark bronze-gold diamond arrangement',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'diamond',
      foreground: '#78350F',
      background: '#FEF3C7',
    },
  },

  // 8. STAR
  {
    id: 'star-astral-midnight',
    name: 'Astral Midnight',
    category: 'Star',
    description: 'Starlight shaped matrix for celestial & magic vibes',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'star',
      foreground: '#1E1B4B',
      background: '#EEF2FF',
    },
  },
  {
    id: 'star-aurora-gold',
    name: 'Aurora Star',
    category: 'Star',
    description: 'Golden stellar points on warm ivory canvas',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'star',
      foreground: '#854D0E',
      background: '#FEF9C3',
    },
  },
  {
    id: 'star-cosmic-purple',
    name: 'Cosmic Stella',
    category: 'Star',
    description: 'Deep cosmic plum with star accents',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'dot',
      cornerDotStyle: 'star',
      foreground: '#581C87',
      background: '#FAF5FF',
    },
  },
  {
    id: 'star-stardust-ruby',
    name: 'Stardust Ruby',
    category: 'Star',
    description: 'Sparkling ruby points on soft rose backdrop',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'star',
      foreground: '#9F1239',
      background: '#FFF1F2',
    },
  },
  {
    id: 'star-cyber-nova',
    name: 'Cyber Nova',
    category: 'Star',
    description: 'Futuristic sci-fi star points in cyan and black',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'star',
      foreground: '#0F172A',
      background: '#CFFAFE',
    },
  },

  // 9. SOFT
  {
    id: 'soft-pastel-mint',
    name: 'Pastel Mint Leaf',
    category: 'Soft',
    description: 'Gentle organic green with rounded soft edges',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#166534',
      background: '#DCFCE7',
    },
  },
  {
    id: 'soft-lavender-mist',
    name: 'Lavender Mist',
    category: 'Soft',
    description: 'Serene lavender with gentle rounded corners',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#4C1D95',
      background: '#EDE9FE',
    },
  },
  {
    id: 'soft-warm-peach',
    name: 'Warm Peach Foam',
    category: 'Soft',
    description: 'Inviting peach and terracotta soothing balance',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'rounded',
      foreground: '#9A3412',
      background: '#FFEDD5',
    },
  },
  {
    id: 'soft-cloud-sky',
    name: 'Cloud Sky',
    category: 'Soft',
    description: 'Airy serene sky blue with rounded modules',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#075985',
      background: '#E0F2FE',
    },
  },
  {
    id: 'soft-butter-cream',
    name: 'Vanilla Butter',
    category: 'Soft',
    description: 'Warm cafe tones for bakery and dessert branding',
    config: {
      dotStyle: 'classy-rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#713F12',
      background: '#FEF9C3',
    },
  },

  // 10. BOLD
  {
    id: 'bld-neo-black',
    name: 'Neo Brutal Black',
    category: 'Bold',
    description: 'Maximum contrast deep black with bold angles',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#FFE600',
    },
  },
  {
    id: 'bld-warning-hazard',
    name: 'Hazard Orange',
    category: 'Bold',
    description: 'High impact safety orange on deep black',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#FB923C',
    },
  },
  {
    id: 'bld-heavy-metal',
    name: 'Heavy Industrial',
    category: 'Bold',
    description: 'Chunky heavy lines for industrial packaging',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#CBD5E1',
    },
  },
  {
    id: 'bld-crimson-punch',
    name: 'Crimson Punch',
    category: 'Bold',
    description: 'High saturated red on crisp snow white',
    config: {
      dotStyle: 'vertical-lines',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#991B1B',
      background: '#FFFFFF',
    },
  },
  {
    id: 'bld-toxic-lime',
    name: 'Acid Lime Brut',
    category: 'Bold',
    description: 'Punchy electric lime and pitch black contrast',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#000000',
      background: '#A3E635',
    },
  },

  // 11. LUXURY
  {
    id: 'lux-monaco-gold',
    name: 'Monaco Gold',
    category: 'Luxury',
    description: 'Refined deep royal gold on warm ivory',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'diamond',
      foreground: '#78350F',
      background: '#FFFDF8',
    },
  },
  {
    id: 'lux-noir-champagne',
    name: 'Noir Champagne',
    category: 'Luxury',
    description: 'High-end champagne metallic tone on deep slate',
    config: {
      dotStyle: 'classy-rounded',
      cornerSquareStyle: 'vintage',
      cornerDotStyle: 'rounded',
      foreground: '#451A03',
      background: '#FEF3C7',
    },
  },
  {
    id: 'lux-royal-platinum',
    name: 'Royal Platinum',
    category: 'Luxury',
    description: 'Subtle platinum sheen with classy module cuts',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'vintage',
      cornerDotStyle: 'square',
      foreground: '#1E293B',
      background: '#F1F5F9',
    },
  },
  {
    id: 'lux-caviar-onyx',
    name: 'Caviar Onyx',
    category: 'Luxury',
    description: 'Velvet black with delicate corner accents for haute couture',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'vintage',
      cornerDotStyle: 'diamond',
      foreground: '#0A0A0A',
      background: '#FAFAFA',
    },
  },
  {
    id: 'lux-rose-gold',
    name: 'Rose Gold Boutique',
    category: 'Luxury',
    description: 'Delicate rose gold tones for perfume and cosmetics',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'rounded',
      foreground: '#881337',
      background: '#FFF1F2',
    },
  },

  // 12. CORPORATE
  {
    id: 'corp-swiss-bank',
    name: 'Swiss Blue',
    category: 'Corporate',
    description: 'Conservative reliable banking navy blue',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#1E3A8A',
      background: '#FFFFFF',
    },
  },
  {
    id: 'corp-consulting-slate',
    name: 'Consulting Slate',
    category: 'Corporate',
    description: 'Crisp graphite slate for corporate business cards',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'rounded',
      foreground: '#1E293B',
      background: '#FFFFFF',
    },
  },
  {
    id: 'corp-fintech-teal',
    name: 'Fintech Teal',
    category: 'Corporate',
    description: 'Modern financial technology dark teal',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#134E4A',
      background: '#F0FDFA',
    },
  },
  {
    id: 'corp-legal-burgundy',
    name: 'Legal Chamber',
    category: 'Corporate',
    description: 'Distinguished burgundy for legal and executive firms',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'square',
      foreground: '#4C0519',
      background: '#FFFFFF',
    },
  },
  {
    id: 'corp-tech-enterprise',
    name: 'Enterprise Cobalt',
    category: 'Corporate',
    description: 'Solid high-trust blue with squircle corners',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'square',
      foreground: '#1D4ED8',
      background: '#F8FAFC',
    },
  },

  // 13. GLASS
  {
    id: 'gls-frost-cyan',
    name: 'Frost Cyan Glass',
    category: 'Glass',
    description: 'Translucent icy blue feel with rounded modules',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#0E7490',
      background: '#E0F2FE',
    },
  },
  {
    id: 'gls-liquid-crystal',
    name: 'Liquid Crystal',
    category: 'Glass',
    description: 'Clean fluid crystal styling on high-clarity background',
    config: {
      dotStyle: 'fluid',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'rounded',
      foreground: '#0284C7',
      background: '#F0F9FF',
    },
  },
  {
    id: 'gls-smoked-quartz',
    name: 'Smoked Quartz',
    category: 'Glass',
    description: 'Smoky tinted glass tones with fluid dots',
    config: {
      dotStyle: 'fluid',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#334155',
      background: '#E2E8F0',
    },
  },
  {
    id: 'gls-aurora-glass',
    name: 'Aurora Prismatic',
    category: 'Glass',
    description: 'Prismatic refraction feel with soft fluid corners',
    config: {
      dotStyle: 'fluid',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#4338CA',
      background: '#EEF2FF',
    },
  },
  {
    id: 'gls-emerald-glass',
    name: 'Bottle Glass Green',
    category: 'Glass',
    description: 'Vintage sea glass green with smooth rounded modules',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#065F46',
      background: '#ECFDF5',
    },
  },

  // 14. NEON
  {
    id: 'neo-cyber-lime',
    name: 'Neon Cyber Lime',
    category: 'Neon',
    description: 'Electric lime foreground on rich dark onyx',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#22C55E',
      background: '#052E16',
    },
  },
  {
    id: 'neo-tokyo-magenta',
    name: 'Tokyo Magenta',
    category: 'Neon',
    description: 'Vibrant electric pink on deep night canvas',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#E11D48',
      background: '#4C0519',
    },
  },
  {
    id: 'neo-electric-cyan',
    name: 'Electric Cyan Glow',
    category: 'Neon',
    description: 'Vivid cyan on deep midnight background',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#06B6D4',
      background: '#083344',
    },
  },
  {
    id: 'neo-solar-flare',
    name: 'Solar Neon Flare',
    category: 'Neon',
    description: 'Radiant neon yellow on warm dark ember background',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'diamond',
      foreground: '#FACC15',
      background: '#451A03',
    },
  },
  {
    id: 'neo-ultraviolet',
    name: 'Ultra Violet Pulse',
    category: 'Neon',
    description: 'High energy laser violet on deep dark purple',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'dot',
      foreground: '#A855F7',
      background: '#3B0764',
    },
  },

  // 15. FUTURISTIC
  {
    id: 'fut-blade-runner',
    name: 'Blade Runner 2099',
    category: 'Futuristic',
    description: 'Angled cybernetic lines with high sci-fi contrast',
    config: {
      dotStyle: 'vertical-lines',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#E2E8F0',
    },
  },
  {
    id: 'fut-quantum-grid',
    name: 'Quantum Grid',
    category: 'Futuristic',
    description: 'Precision quantum grid styling in deep blue',
    config: {
      dotStyle: 'horizontal-lines',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'square',
      foreground: '#1E3A8A',
      background: '#EFF6FF',
    },
  },
  {
    id: 'fut-hologram-cyan',
    name: 'Holographic Blue',
    category: 'Futuristic',
    description: 'Hologram terminal theme with geometric dots',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'dot',
      foreground: '#0284C7',
      background: '#F0F9FF',
    },
  },
  {
    id: 'fut-mecha-core',
    name: 'Mecha Core',
    category: 'Futuristic',
    description: 'Heavy armor plating shapes and bold industrial frame',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'diamond',
      foreground: '#18181B',
      background: '#F4F4F5',
    },
  },
  {
    id: 'fut-orbital-space',
    name: 'Orbital Station',
    category: 'Futuristic',
    description: 'Minimalist spacecraft telemetry style in titanium',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'dot',
      foreground: '#0369A1',
      background: '#E0F2FE',
    },
  },

  // 16. GAMING
  {
    id: 'game-respawn-red',
    name: 'Respawn Red',
    category: 'Gaming',
    description: 'Aggressive esports red on tactical white',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#B91C1C',
      background: '#FFFFFF',
    },
  },
  {
    id: 'game-lootbox-gold',
    name: 'Legendary Loot',
    category: 'Gaming',
    description: 'Golden legendary drop styling with star dots',
    config: {
      dotStyle: 'star',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'star',
      foreground: '#854D0E',
      background: '#FEF08A',
    },
  },
  {
    id: 'game-discord-blurple',
    name: 'Gamer Blurple',
    category: 'Gaming',
    description: 'Community gamer blurple with rounded squircle',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#4338CA',
      background: '#EEF2FF',
    },
  },
  {
    id: 'game-boss-fight',
    name: 'Boss Fight Crimson',
    category: 'Gaming',
    description: 'Ominous deep crimson pixel layout for gaming badges',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#881337',
      background: '#FFE4E6',
    },
  },
  {
    id: 'game-mana-potion',
    name: 'Mana Potion Blue',
    category: 'Gaming',
    description: 'Vibrant arcade blue with diamond points',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'diamond',
      foreground: '#0284C7',
      background: '#BAE6FD',
    },
  },

  // 17. CUTE
  {
    id: 'cute-strawberry-milk',
    name: 'Strawberry Milk',
    category: 'Cute',
    description: 'Sweet pastel pink with heart shaped modules',
    config: {
      dotStyle: 'heart',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'heart',
      foreground: '#BE185D',
      background: '#FDF2F8',
    },
  },
  {
    id: 'cute-banana-split',
    name: 'Banana Split',
    category: 'Cute',
    description: 'Sunny warm yellow and chocolate brown points',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#713F12',
      background: '#FEF9C3',
    },
  },
  {
    id: 'cute-marshmallow',
    name: 'Marshmallow Cloud',
    category: 'Cute',
    description: 'Super rounded puffy clouds in lilac purple',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#6D28D9',
      background: '#F5F3FF',
    },
  },
  {
    id: 'cute-matcha-cookie',
    name: 'Matcha Cookie',
    category: 'Cute',
    description: 'Sweet matcha green with friendly rounded curves',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'dot',
      foreground: '#15803D',
      background: '#DCFCE7',
    },
  },
  {
    id: 'cute-boba-tea',
    name: 'Brown Sugar Boba',
    category: 'Cute',
    description: 'Sweet caramel brown dots for cafe and dessert brands',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#78350F',
      background: '#FFEDD5',
    },
  },

  // 18. ELEGANT
  {
    id: 'elg-calligraphy-ink',
    name: 'Calligraphy Ink',
    category: 'Elegant',
    description: 'Fluid sophisticated strokes for weddings and art',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'vintage',
      cornerDotStyle: 'rounded',
      foreground: '#0F172A',
      background: '#F8FAFC',
    },
  },
  {
    id: 'elg-tuscan-olive',
    name: 'Tuscan Olive',
    category: 'Elegant',
    description: 'Rich warm olive green on gentle travertine ivory',
    config: {
      dotStyle: 'classy-rounded',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'dot',
      foreground: '#3F6212',
      background: '#FEFCE8',
    },
  },
  {
    id: 'elg-venice-terracotta',
    name: 'Venice Terracotta',
    category: 'Elegant',
    description: 'Warm artisan terracotta on pale linen background',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'vintage',
      cornerDotStyle: 'square',
      foreground: '#9A3412',
      background: '#FFF7ED',
    },
  },
  {
    id: 'elg-chiffon-slate',
    name: 'Chiffon Slate',
    category: 'Elegant',
    description: 'Whisper soft slate tones with delicate rounded corners',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#334155',
      background: '#FFFFFF',
    },
  },
  {
    id: 'elg-vienna-gold',
    name: 'Vienna Imperial',
    category: 'Elegant',
    description: 'Gilded regal elegance for luxury events and invitations',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'diamond',
      foreground: '#854D0E',
      background: '#FFFBEB',
    },
  },

  // 19. RETRO
  {
    id: 'ret-cassette-70s',
    name: '1975 Cassette',
    category: 'Retro',
    description: 'Groovy warm mustard and deep umber retro vibe',
    config: {
      dotStyle: 'extra-rounded',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#78350F',
      background: '#FDE68A',
    },
  },
  {
    id: 'ret-polaroid-warm',
    name: 'Polaroid Instant',
    category: 'Retro',
    description: 'Faded warm vintage tones on photo paper off-white',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'square',
      foreground: '#292524',
      background: '#F5F5F4',
    },
  },
  {
    id: 'ret-synthwave-sunset',
    name: 'Synthwave 84',
    category: 'Retro',
    description: 'Hot sunset magenta on twilight lilac',
    config: {
      dotStyle: 'horizontal-lines',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#BE185D',
      background: '#FDF2F8',
    },
  },
  {
    id: 'ret-vhs-scanlines',
    name: 'VHS Tape Scan',
    category: 'Retro',
    description: 'Horizontal line modules resembling classic analog television',
    config: {
      dotStyle: 'horizontal-lines',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#E2E8F0',
    },
  },
  {
    id: 'ret-diner-mint',
    name: '50s Route 66 Diner',
    category: 'Retro',
    description: 'Cheery diner turquoise with rounded retro badges',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#0F766E',
      background: '#CCFBF1',
    },
  },

  // 20. GRADIENT
  {
    id: 'grd-sunset-blaze',
    name: 'Sunset Blaze',
    category: 'Gradient',
    description: 'Vivid orange to crimson gradient on crisp white',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'rounded',
      cornerDotStyle: 'dot',
      foreground: '#EA580C',
      background: '#FFFFFF',
      gradient: {
        type: 'linear',
        color1: '#EA580C',
        color2: '#BE123C',
        angle: 45,
      },
    },
  },
  {
    id: 'grd-ocean-depths',
    name: 'Ocean Depths',
    category: 'Gradient',
    description: 'Teal to deep royal navy gradient with high readability',
    config: {
      dotStyle: 'classy-rounded',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#0D9488',
      background: '#FFFFFF',
      gradient: {
        type: 'linear',
        color1: '#0D9488',
        color2: '#1E3A8A',
        angle: 135,
      },
    },
  },
  {
    id: 'grd-electric-aurora',
    name: 'Electric Aurora',
    category: 'Gradient',
    description: 'Vivid violet to electric indigo transition',
    config: {
      dotStyle: 'rounded',
      cornerSquareStyle: 'extra-rounded',
      cornerDotStyle: 'dot',
      foreground: '#7C3AED',
      background: '#FFFFFF',
      gradient: {
        type: 'linear',
        color1: '#7C3AED',
        color2: '#2563EB',
        angle: 90,
      },
    },
  },
  {
    id: 'grd-emerald-glow',
    name: 'Emerald Forest Glow',
    category: 'Gradient',
    description: 'Deep forest to electric lime gradient',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'pill',
      cornerDotStyle: 'rounded',
      foreground: '#047857',
      background: '#FFFFFF',
      gradient: {
        type: 'linear',
        color1: '#047857',
        color2: '#16A34A',
        angle: 60,
      },
    },
  },
  {
    id: 'grd-copper-gold',
    name: 'Molten Copper',
    category: 'Gradient',
    description: 'Rich molten bronze to glowing amber gradient',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'diamond',
      foreground: '#C2410C',
      background: '#FFFBEB',
      gradient: {
        type: 'linear',
        color1: '#C2410C',
        color2: '#B45309',
        angle: 120,
      },
    },
  },

  // 21. TECH
  {
    id: 'tch-silicon-chip',
    name: 'Silicon Microchip',
    category: 'Tech',
    description: 'Circuit board aesthetics with vertical trace modules',
    config: {
      dotStyle: 'vertical-lines',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#064E3B',
      background: '#ECFDF5',
    },
  },
  {
    id: 'tch-terminal-green',
    name: 'CRT Terminal',
    category: 'Tech',
    description: 'Retro phosphor green lines on dark terminal screen',
    config: {
      dotStyle: 'pixel',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#22C55E',
      background: '#022C22',
    },
  },
  {
    id: 'tch-ai-neural',
    name: 'Neural Node',
    category: 'Tech',
    description: 'Clean scientific neural dots with rounded nodes',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'dot',
      foreground: '#1E1B4B',
      background: '#F5F3FF',
    },
  },
  {
    id: 'tch-cyber-security',
    name: 'Vault Security',
    category: 'Tech',
    description: 'Hardened security vault double ring finder patterns',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'square',
      foreground: '#0F172A',
      background: '#F8FAFC',
    },
  },
  {
    id: 'tch-biometric-scan',
    name: 'Biometric Grid',
    category: 'Tech',
    description: 'High-tech biometric scanner layout in deep cobalt',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'squircle',
      cornerDotStyle: 'rounded',
      foreground: '#1D4ED8',
      background: '#EFF6FF',
    },
  },

  // 22. GEOMETRIC
  {
    id: 'geo-bauhaus-bold',
    name: 'Bauhaus Master',
    category: 'Geometric',
    description: 'Primary geometric forms inspired by Bauhaus design',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'dot',
      foreground: '#000000',
      background: '#FFE600',
    },
  },
  {
    id: 'geo-mondrian-block',
    name: 'Mondrian Pure',
    category: 'Geometric',
    description: 'De Stijl stark black lines on crisp primary canvas',
    config: {
      dotStyle: 'square',
      cornerSquareStyle: 'square',
      cornerDotStyle: 'square',
      foreground: '#172554',
      background: '#FEF2F2',
    },
  },
  {
    id: 'geo-diagonal-matrix',
    name: 'Diagonal Vector',
    category: 'Geometric',
    description: 'Sharply angled diamond nodes on minimal light base',
    config: {
      dotStyle: 'diamond',
      cornerSquareStyle: 'diamond',
      cornerDotStyle: 'diamond',
      foreground: '#18181B',
      background: '#FAFAFA',
    },
  },
  {
    id: 'geo-concentric-rings',
    name: 'Concentric Target',
    category: 'Geometric',
    description: 'Nested rounded circles with dot matrix center',
    config: {
      dotStyle: 'dots',
      cornerSquareStyle: 'double',
      cornerDotStyle: 'dot',
      foreground: '#0F172A',
      background: '#FFFFFF',
    },
  },
  {
    id: 'geo-prism-hex',
    name: 'Prism Geometry',
    category: 'Geometric',
    description: 'Precision angular elements with high contrast output',
    config: {
      dotStyle: 'classy',
      cornerSquareStyle: 'bold-angle',
      cornerDotStyle: 'square',
      foreground: '#312E81',
      background: '#EEF2FF',
    },
  },
];

// Dynamically generate extra diverse variations to exceed 100+ presets
const EXTRA_THEMES = [
  { name: 'Brutalist Punch', cat: 'Bold', fg: '#000000', bg: '#FF5E5B', dot: 'square', cs: 'bold-angle', cd: 'square' },
  { name: 'Electric Mint', cat: 'Modern', fg: '#064E3B', bg: '#6EE7B7', dot: 'rounded', cs: 'squircle', cd: 'rounded' },
  { name: 'Solaris Warmth', cat: 'Retro', fg: '#7C2D12', bg: '#FDE047', dot: 'extra-rounded', cs: 'pill', cd: 'dot' },
  { name: 'Deep Space Navy', cat: 'Minimal', fg: '#020617', bg: '#F8FAFC', dot: 'square', cs: 'square', cd: 'square' },
  { name: 'Crimson Velvet', cat: 'Luxury', fg: '#4C0519', bg: '#FFF1F2', dot: 'classy', cs: 'double', cd: 'diamond' },
  { name: 'Matcha Foam', cat: 'Soft', fg: '#14532D', bg: '#F0FDF4', dot: 'rounded', cs: 'extra-rounded', cd: 'rounded' },
  { name: 'Steel & Copper', cat: 'Corporate', fg: '#334155', bg: '#FFEDD5', dot: 'classy', cs: 'rounded', cd: 'dot' },
  { name: 'Midnight Cyan', cat: 'Neon', fg: '#22D3EE', bg: '#082F49', dot: 'dots', cs: 'rounded', cd: 'dot' },
  { name: 'Golden Honey', cat: 'Elegant', fg: '#78350F', bg: '#FEF3C7', dot: 'diamond', cs: 'double', cd: 'diamond' },
  { name: 'Lilac Cloud', cat: 'Cute', fg: '#581C87', bg: '#F3E8FF', dot: 'heart', cs: 'pill', cd: 'heart' },
];

EXTRA_THEMES.forEach((theme, idx) => {
  STYLE_PRESETS.push({
    id: `extra-preset-${idx + 1}`,
    name: theme.name,
    category: theme.cat as StyleCategory,
    description: `Distinctive ${theme.name.toLowerCase()} design crafted for modern brands`,
    config: {
      dotStyle: theme.dot as any,
      cornerSquareStyle: theme.cs as any,
      cornerDotStyle: theme.cd as any,
      foreground: theme.fg,
      background: theme.bg,
    },
  });
});
